#!/usr/bin/env node
// Generates n2.html from n4.html template + embedded kanji data
const fs = require('fs');
const path = require('path');

// Compact format: [kanji, on, kun, meaning, [[word,reading,meaning],...], antonym]
// on/kun are comma-separated strings, antonym is "" for null
const DATA = [
["党","トウ","","party; faction",[["政党","せいとう","political party"],["党員","とういん","party member"],["与党","よとう","ruling party"]],""],
["協","キョウ","","cooperate; together",[["協力","きょうりょく","cooperation"],["協会","きょうかい","association"],["協議","きょうぎ","conference"]],""],
["総","ソウ","す.べて","overall; general",[["総理","そうり","prime minister"],["総合","そうごう","comprehensive"],["総額","そうがく","total amount"]],""],
["区","ク","","ward; district",[["区別","くべつ","distinction"],["地区","ちく","district"],["区域","くいき","area"]],""],
["領","リョウ","","territory; dominion",[["領土","りょうど","territory"],["大統領","だいとうりょう","president"],["領事","りょうじ","consul"]],""],
["県","ケン","","prefecture",[["県庁","けんちょう","prefectural office"],["県民","けんみん","prefectural residents"],["県立","けんりつ","prefectural"]],""],
["設","セツ","もう.ける","establish; set up",[["設計","せっけい","design"],["建設","けんせつ","construction"],["設備","せつび","equipment"]],""],
["改","カイ","あらた.める","reform; renew",[["改善","かいぜん","improvement"],["改正","かいせい","revision"],["改革","かいかく","reform"]],""],
["府","フ","","government; urban prefecture",[["政府","せいふ","government"],["府県","ふけん","prefectures"],["大阪府","おおさかふ","Osaka Prefecture"]],""],
["査","サ","","investigate; inspect",[["調査","ちょうさ","investigation"],["検査","けんさ","inspection"],["捜査","そうさ","criminal investigation"]],""],
["委","イ","ゆだ.ねる","committee; entrust",[["委員","いいん","committee member"],["委員会","いいんかい","committee"],["委託","いたく","consignment"]],""],
["軍","グン","いくさ","army; military",[["軍隊","ぐんたい","army"],["軍事","ぐんじ","military affairs"],["海軍","かいぐん","navy"]],""],
["団","ダン,トン","","group; association",[["団体","だんたい","organization"],["集団","しゅうだん","group"],["布団","ふとん","futon"]],""],
["各","カク","おのおの","each; every",[["各地","かくち","every place"],["各国","かっこく","each country"],["各自","かくじ","each person"]],""],
["島","トウ","しま","island",[["半島","はんとう","peninsula"],["島国","しまぐに","island country"],["列島","れっとう","archipelago"]],""],
["革","カク","かわ","leather; reform",[["革命","かくめい","revolution"],["改革","かいかく","reform"],["皮革","ひかく","leather"]],""],
["村","ソン","むら","village",[["村長","そんちょう","village chief"],["村民","そんみん","villager"],["農村","のうそん","farming village"]],""],
["勢","セイ","いきお.い","force; energy",[["勢い","いきおい","vigor"],["姿勢","しせい","posture"],["勢力","せいりょく","influence"]],""],
["減","ゲン","へ.る,へ.らす","decrease; reduce",[["減る","へる","to decrease"],["減少","げんしょう","decrease"],["削減","さくげん","reduction"]],"増"],
["再","サイ","ふたた.び","again; twice",[["再び","ふたたび","again"],["再生","さいせい","regeneration"],["再開","さいかい","reopening"]],""],
["税","ゼイ","","tax",[["税金","ぜいきん","tax"],["消費税","しょうひぜい","consumption tax"],["税関","ぜいかん","customs"]],""],
["営","エイ","いとな.む","manage; operate",[["営業","えいぎょう","business"],["経営","けいえい","management"],["営む","いとなむ","to manage"]],""],
["比","ヒ","くら.べる","compare; ratio",[["比べる","くらべる","to compare"],["比較","ひかく","comparison"],["比率","ひりつ","ratio"]],""],
["防","ボウ","ふせ.ぐ","defend; prevent",[["防ぐ","ふせぐ","to prevent"],["予防","よぼう","prevention"],["防止","ぼうし","prevention"]],""],
["補","ホ","おぎな.う","supplement; compensate",[["補う","おぎなう","to supplement"],["候補","こうほ","candidate"],["補助","ほじょ","assistance"]],""],
["境","キョウ,ケイ","さかい","boundary; border",[["環境","かんきょう","environment"],["国境","こっきょう","national border"],["境界","きょうかい","boundary"]],""],
["導","ドウ","みちび.く","guide; lead",[["指導","しどう","guidance"],["導入","どうにゅう","introduction"],["導く","みちびく","to guide"]],""],
["副","フク","","vice-; sub-",[["副社長","ふくしゃちょう","vice president"],["副作用","ふくさよう","side effect"],["副業","ふくぎょう","side job"]],"正"],
["算","サン","","calculate",[["計算","けいさん","calculation"],["予算","よさん","budget"],["算数","さんすう","arithmetic"]],""],
["輸","ユ","","transport; send",[["輸出","ゆしゅつ","export"],["輸入","ゆにゅう","import"],["輸送","ゆそう","transport"]],""],
["述","ジュツ","の.べる","state; mention",[["述べる","のべる","to state"],["記述","きじゅつ","description"],["著述","ちょじゅつ","writing"]],""],
["線","セン","","line",[["新幹線","しんかんせん","bullet train"],["路線","ろせん","route"],["直線","ちょくせん","straight line"]],""],
["農","ノウ","","agriculture; farming",[["農業","のうぎょう","agriculture"],["農家","のうか","farmer"],["農村","のうそん","farming village"]],""],
["州","シュウ","す","state; province",[["九州","きゅうしゅう","Kyushu"],["本州","ほんしゅう","Honshu"],["欧州","おうしゅう","Europe"]],""],
["武","ブ,ム","たけ","warrior; military",[["武器","ぶき","weapon"],["武士","ぶし","samurai"],["武道","ぶどう","martial arts"]],"文"],
["象","ショウ,ゾウ","","elephant; phenomenon",[["対象","たいしょう","target"],["現象","げんしょう","phenomenon"],["印象","いんしょう","impression"]],""],
["域","イキ","","area; region",[["地域","ちいき","region"],["区域","くいき","zone"],["領域","りょういき","domain"]],""],
["額","ガク","ひたい","amount; forehead",[["金額","きんがく","amount of money"],["総額","そうがく","total amount"],["額縁","がくぶち","picture frame"]],""],
["欧","オウ","","Europe",[["欧米","おうべい","Europe and America"],["欧州","おうしゅう","Europe"],["北欧","ほくおう","Northern Europe"]],""],
["担","タン","かつ.ぐ,にな.う","carry; bear",[["担当","たんとう","in charge"],["負担","ふたん","burden"],["担う","になう","to bear"]],""],
["準","ジュン","","standard; quasi-",[["準備","じゅんび","preparation"],["基準","きじゅん","standard"],["水準","すいじゅん","level"]],""],
["賞","ショウ","","prize; praise",[["賞品","しょうひん","prize"],["受賞","じゅしょう","winning a prize"],["鑑賞","かんしょう","appreciation"]],""],
["辺","ヘン","あた.り","vicinity; side",[["辺り","あたり","vicinity"],["周辺","しゅうへん","surroundings"],["海辺","うみべ","seaside"]],""],
["造","ゾウ","つく.る","create; build",[["製造","せいぞう","manufacture"],["構造","こうぞう","structure"],["造る","つくる","to build"]],""],
["被","ヒ","こうむ.る","suffer; incur",[["被害","ひがい","damage"],["被害者","ひがいしゃ","victim"],["被る","こうむる","to suffer"]],""],
["技","ギ","わざ","skill; technique",[["技術","ぎじゅつ","technology"],["技能","ぎのう","skill"],["演技","えんぎ","performance"]],""],
["低","テイ","ひく.い,ひく.める","low; short",[["低い","ひくい","low"],["最低","さいてい","minimum"],["低下","ていか","decline"]],"高"],
["復","フク","","restore; return",[["回復","かいふく","recovery"],["復活","ふっかつ","revival"],["往復","おうふく","round trip"]],""],
["移","イ","うつ.る,うつ.す","move; shift",[["移動","いどう","movement"],["移転","いてん","relocation"],["移る","うつる","to move"]],""],
["個","コ","","individual; counter",[["個人","こじん","individual"],["個性","こせい","individuality"],["個別","こべつ","separate"]],""],
// PAGE 2
["門","モン","かど","gate; door",[["専門","せんもん","specialty"],["部門","ぶもん","division"],["門","もん","gate"]],""],
["課","カ","","section; lesson",[["課長","かちょう","section chief"],["課題","かだい","task"],["日課","にっか","daily routine"]],""],
["脳","ノウ","","brain",[["頭脳","ずのう","brains"],["脳裏","のうり","back of mind"],["洗脳","せんのう","brainwashing"]],""],
["極","キョク,ゴク","きわ.める","extreme; pole",[["積極的","せっきょくてき","proactive"],["北極","ほっきょく","North Pole"],["極める","きわめる","to master"]],""],
["含","ガン","ふく.む,ふく.める","contain; include",[["含む","ふくむ","to contain"],["含める","ふくめる","to include"],["含有","がんゆう","containing"]],""],
["蔵","ゾウ,クラ","くら","storehouse; keep",[["冷蔵庫","れいぞうこ","refrigerator"],["蔵","くら","storehouse"],["貯蔵","ちょぞう","storage"]],""],
["量","リョウ","はか.る","quantity; measure",[["量","りょう","quantity"],["大量","たいりょう","large quantity"],["重量","じゅうりょう","weight"]],""],
["型","ケイ","かた","type; model; mold",[["大型","おおがた","large-sized"],["型","かた","type"],["模型","もけい","model"]],""],
["況","キョウ","","condition; situation",[["状況","じょうきょう","situation"],["況して","まして","much more"],["好況","こうきょう","boom"]],""],
["針","シン","はり","needle; policy",[["方針","ほうしん","policy"],["針","はり","needle"],["時計の針","とけいのはり","clock hand"]],""],
["専","セン","もっぱ.ら","specialty; exclusive",[["専門","せんもん","specialty"],["専用","せんよう","exclusive use"],["専ら","もっぱら","exclusively"]],""],
["谷","コク","たに","valley",[["谷","たに","valley"],["谷間","たにま","ravine"],["渓谷","けいこく","gorge"]],""],
["史","シ","","history",[["歴史","れきし","history"],["史上","しじょう","in history"],["史料","しりょう","historical materials"]],""],
["階","カイ","","floor; story; stage",[["階段","かいだん","stairs"],["段階","だんかい","stage"],["地階","ちかい","basement"]],""],
["管","カン","くだ","pipe; control",[["管理","かんり","management"],["管轄","かんかつ","jurisdiction"],["血管","けっかん","blood vessel"]],""],
["兵","ヘイ,ヒョウ","","soldier; army",[["兵士","へいし","soldier"],["兵器","へいき","weapon"],["兵隊","へいたい","troops"]],""],
["接","セツ","つ.ぐ","connect; contact",[["接する","せっする","to come in contact"],["直接","ちょくせつ","direct"],["面接","めんせつ","interview"]],""],
["細","サイ","ほそ.い,こま.かい","thin; fine; detailed",[["細い","ほそい","thin"],["細かい","こまかい","detailed"],["詳細","しょうさい","details"]],"太"],
["効","コウ","き.く","effect; merit",[["効果","こうか","effect"],["有効","ゆうこう","effective"],["効く","きく","to be effective"]],""],
["丸","ガン","まる,まる.い","round; circle",[["丸い","まるい","round"],["丸","まる","circle"],["日の丸","ひのまる","Japanese flag"]],""],
["湾","ワン","","bay; gulf",[["湾","わん","bay"],["台湾","たいわん","Taiwan"],["湾岸","わんがん","bay coast"]],""],
["録","ロク","","record; register",[["記録","きろく","record"],["録音","ろくおん","recording"],["登録","とうろく","registration"]],""],
["省","ショウ,セイ","かえり.みる,はぶ.く","ministry; reflect; omit",[["省く","はぶく","to omit"],["反省","はんせい","reflection"],["省エネ","しょうエネ","energy saving"]],""],
["旧","キュウ","ふる.い","old; former",[["旧式","きゅうしき","old-fashioned"],["復旧","ふっきゅう","restoration"],["旧姓","きゅうせい","maiden name"]],"新"],
["橋","キョウ","はし","bridge",[["橋","はし","bridge"],["歩道橋","ほどうきょう","pedestrian bridge"],["鉄橋","てっきょう","railway bridge"]],""],
["岸","ガン","きし","shore; bank",[["海岸","かいがん","coast"],["岸","きし","shore"],["対岸","たいがん","opposite shore"]],""],
["周","シュウ","まわ.り","circumference; around",[["周り","まわり","surroundings"],["周辺","しゅうへん","vicinity"],["一周","いっしゅう","one lap"]],""],
["材","ザイ","","material; timber",[["材料","ざいりょう","materials"],["素材","そざい","raw material"],["人材","じんざい","human resources"]],""],
["戸","コ","と","door; counter for houses",[["戸","と","door"],["戸口","とぐち","doorway"],["戸棚","とだな","cupboard"]],""],
["央","オウ","","center; middle",[["中央","ちゅうおう","center"],["中央線","ちゅうおうせん","Chuo Line"]],""],
["券","ケン","","ticket; certificate",[["切符","きっぷ","ticket"],["乗車券","じょうしゃけん","passenger ticket"],["入場券","にゅうじょうけん","admission ticket"]],""],
["編","ヘン","あ.む","knit; compile; edit",[["編集","へんしゅう","editing"],["編む","あむ","to knit"],["長編","ちょうへん","full-length"]],""],
["捜","ソウ","さが.す","search; look for",[["捜す","さがす","to search"],["捜査","そうさ","investigation"],["捜索","そうさく","search"]],""],
["竹","チク","たけ","bamboo",[["竹","たけ","bamboo"],["竹林","ちくりん","bamboo grove"],["爆竹","ばくちく","firecracker"]],""],
["超","チョウ","こ.える,こ.す","exceed; super-",[["超える","こえる","to exceed"],["超過","ちょうか","excess"],["超人","ちょうじん","superhuman"]],""],
["並","ヘイ","なみ,なら.べる,なら.ぶ","line up; ordinary",[["並べる","ならべる","to line up"],["並ぶ","ならぶ","to stand in line"],["並行","へいこう","parallel"]],""],
["療","リョウ","","heal; cure",[["治療","ちりょう","treatment"],["療法","りょうほう","remedy"],["医療","いりょう","medical care"]],""],
["採","サイ","と.る","pick; gather; employ",[["採用","さいよう","adoption"],["採る","とる","to pick"],["採点","さいてん","grading"]],""],
["森","シン","もり","forest",[["森","もり","forest"],["森林","しんりん","forest"],["森林浴","しんりんよく","forest bathing"]],""],
["競","キョウ,ケイ","きそ.う,せ.る","compete; vie",[["競争","きょうそう","competition"],["競技","きょうぎ","athletic event"],["競馬","けいば","horse racing"]],""],
["介","カイ","","mediate; concern",[["紹介","しょうかい","introduction"],["介護","かいご","nursing care"],["仲介","ちゅうかい","mediation"]],""],
["根","コン","ね","root; base",[["根","ね","root"],["根本","こんぽん","fundamental"],["屋根","やね","roof"]],""],
["販","ハン","","sell; trade",[["販売","はんばい","sales"],["自動販売機","じどうはんばいき","vending machine"],["通販","つうはん","mail order"]],""],
["歴","レキ","","history; career",[["歴史","れきし","history"],["学歴","がくれき","educational background"],["経歴","けいれき","career"]],""],
["将","ショウ","","general; commander; future",[["将来","しょうらい","future"],["将軍","しょうぐん","general"],["将棋","しょうぎ","shogi"]],""],
["幅","フク","はば","width; breadth",[["幅","はば","width"],["幅広い","はばひろい","wide"],["振幅","しんぷく","amplitude"]],""],
["般","ハン","","general; sort; carry",[["一般","いっぱん","general"],["一般的","いっぱんてき","common"],["全般","ぜんぱん","overall"]],""],
["貿","ボウ","","trade",[["貿易","ぼうえき","trade"],["自由貿易","じゆうぼうえき","free trade"]],""],
["講","コウ","","lecture; club",[["講義","こうぎ","lecture"],["講演","こうえん","speech"],["講師","こうし","lecturer"]],""],
["林","リン","はやし","grove; forest",[["林","はやし","grove"],["森林","しんりん","forest"],["林業","りんぎょう","forestry"]],""],
// PAGE 3
["装","ソウ,ショウ","よそお.う","attire; equip",[["服装","ふくそう","attire"],["装置","そうち","device"],["装う","よそおう","to dress up"]],""],
["諸","ショ","もろ","various; many",[["諸国","しょこく","various countries"],["諸島","しょとう","archipelago"],["諸々","もろもろ","various"]],""],
["劇","ゲキ","","drama; play; intense",[["劇場","げきじょう","theater"],["演劇","えんげき","drama"],["劇的","げきてき","dramatic"]],""],
["河","カ","かわ","river",[["河川","かせん","rivers"],["河口","かこう","river mouth"],["銀河","ぎんが","galaxy"]],""],
["航","コウ","","navigate; sail; fly",[["航空","こうくう","aviation"],["航海","こうかい","voyage"],["就航","しゅうこう","going into service"]],""],
["鉄","テツ","","iron; steel",[["鉄道","てつどう","railway"],["地下鉄","ちかてつ","subway"],["鉄橋","てっきょう","iron bridge"]],""],
["児","ジ,ニ","","child; infant",[["幼児","ようじ","infant"],["児童","じどう","children"],["小児科","しょうにか","pediatrics"]],""],
["禁","キン","","prohibit; forbid",[["禁止","きんし","prohibition"],["禁煙","きんえん","no smoking"],["厳禁","げんきん","strictly prohibited"]],""],
["印","イン","しるし","mark; seal; print",[["印象","いんしょう","impression"],["印刷","いんさつ","printing"],["目印","めじるし","landmark"]],""],
["逆","ギャク","さか,さか.らう","reverse; opposite",[["逆","ぎゃく","reverse"],["逆転","ぎゃくてん","reversal"],["逆らう","さからう","to oppose"]],"順"],
["換","カン","か.える,か.わる","exchange; replace",[["交換","こうかん","exchange"],["換気","かんき","ventilation"],["換える","かえる","to exchange"]],""],
["久","キュウ,ク","ひさ.しい","long time; old story",[["久しい","ひさしい","long time"],["久しぶり","ひさしぶり","long time no see"],["永久","えいきゅう","eternal"]],""],
["短","タン","みじか.い","short",[["短い","みじかい","short"],["短期","たんき","short-term"],["短所","たんしょ","weak point"]],"長"],
["油","ユ","あぶら","oil; fat",[["石油","せきゆ","petroleum"],["油","あぶら","oil"],["醤油","しょうゆ","soy sauce"]],""],
["暴","ボウ","あば.く,あば.れる","violence; expose",[["暴力","ぼうりょく","violence"],["暴風","ぼうふう","storm"],["暴れる","あばれる","to rage"]],""],
["輪","リン","わ","wheel; ring; circle",[["車輪","しゃりん","wheel"],["指輪","ゆびわ","ring"],["輪","わ","ring"]],""],
["占","セン","し.める,うらな.う","occupy; fortune-telling",[["占める","しめる","to occupy"],["占い","うらない","fortune-telling"],["独占","どくせん","monopoly"]],""],
["植","ショク","う.える,う.わる","plant; grow",[["植物","しょくぶつ","plant"],["植える","うえる","to plant"],["植民地","しょくみんち","colony"]],""],
["清","セイ,ショウ","きよ.い,きよ.める","clean; pure",[["清潔","せいけつ","clean"],["清い","きよい","pure"],["清掃","せいそう","cleaning"]],""],
["倍","バイ","","double; times",[["倍","ばい","double"],["二倍","にばい","twice"],["倍増","ばいぞう","doubling"]],"半"],
["均","キン","","equal; level; average",[["平均","へいきん","average"],["均一","きんいつ","uniform"],["均等","きんとう","equal"]],""],
["億","オク","","hundred million",[["億","おく","hundred million"],["一億","いちおく","one hundred million"],["数億","すうおく","several hundred million"]],""],
["圧","アツ","","pressure; push",[["圧力","あつりょく","pressure"],["気圧","きあつ","atmospheric pressure"],["血圧","けつあつ","blood pressure"]],""],
["芸","ゲイ","","art; performance",[["芸術","げいじゅつ","art"],["芸能","げいのう","entertainment"],["芸人","げいにん","entertainer"]],""],
["署","ショ","","station; government office",[["警察署","けいさつしょ","police station"],["署名","しょめい","signature"],["消防署","しょうぼうしょ","fire station"]],""],
["伸","シン","の.びる,の.ばす","stretch; extend",[["伸びる","のびる","to stretch"],["伸ばす","のばす","to extend"],["伸縮","しんしゅく","expansion"]],"縮"],
["停","テイ","","halt; stop",[["停止","ていし","stop"],["バス停","バスてい","bus stop"],["停電","ていでん","power outage"]],""],
["爆","バク","","bomb; explode",[["爆発","ばくはつ","explosion"],["爆弾","ばくだん","bomb"],["爆破","ばくは","blasting"]],""],
["陸","リク","","land; shore",[["大陸","たいりく","continent"],["陸上","りくじょう","on land"],["上陸","じょうりく","landing"]],"海"],
["玉","ギョク","たま","ball; jewel",[["玉","たま","ball"],["目玉","めだま","eyeball"],["宝玉","ほうぎょく","jewel"]],""],
["波","ハ","なみ","wave",[["波","なみ","wave"],["電波","でんぱ","radio wave"],["津波","つなみ","tsunami"]],""],
["帯","タイ","おび,お.びる","belt; zone; wear",[["地帯","ちたい","zone"],["熱帯","ねったい","tropics"],["帯","おび","belt"]],""],
["延","エン","の.びる,の.ばす,の.べる","extend; postpone",[["延長","えんちょう","extension"],["延びる","のびる","to extend"],["延期","えんき","postponement"]],""],
["羽","ウ","はね,は","feather; wing",[["羽","はね","feather"],["羽根","はね","feather"],["羽毛","うもう","down"]],""],
["固","コ","かた.める,かた.まる,かた.い","harden; solid",[["固い","かたい","hard"],["固定","こてい","fixed"],["固める","かためる","to harden"]],""],
["則","ソク","","rule; law",[["規則","きそく","rule"],["法則","ほうそく","law"],["原則","げんそく","principle"]],""],
["乱","ラン","みだ.れる,みだ.す","disorder; chaos",[["混乱","こんらん","confusion"],["乱れる","みだれる","to be disordered"],["反乱","はんらん","rebellion"]],""],
["普","フ","","universal; general",[["普通","ふつう","ordinary"],["普及","ふきゅう","spread"],["普段","ふだん","usual"]],""],
["測","ソク","はか.る","measure; survey",[["測定","そくてい","measurement"],["観測","かんそく","observation"],["予測","よそく","prediction"]],""],
["豊","ホウ","ゆた.か","abundant; rich",[["豊か","ゆたか","abundant"],["豊富","ほうふ","abundant"],["豊作","ほうさく","good harvest"]],""],
["厚","コウ","あつ.い","thick; kind",[["厚い","あつい","thick"],["厚生","こうせい","welfare"],["厚さ","あつさ","thickness"]],"薄"],
["齢","レイ","","age; years",[["年齢","ねんれい","age"],["高齢","こうれい","advanced age"],["適齢","てきれい","suitable age"]],""],
["囲","イ","かこ.む,かこ.う","surround; enclose",[["囲む","かこむ","to surround"],["周囲","しゅうい","surroundings"],["範囲","はんい","range"]],""],
["卒","ソツ","","graduate; end",[["卒業","そつぎょう","graduation"],["卒論","そつろん","thesis"],["卒業式","そつぎょうしき","graduation ceremony"]],""],
["略","リャク","","abbreviation; strategy",[["省略","しょうりゃく","omission"],["戦略","せんりゃく","strategy"],["略語","りゃくご","abbreviation"]],""],
["承","ショウ","うけたまわ.る","hear; consent; inherit",[["承知","しょうち","consent"],["承認","しょうにん","approval"],["了承","りょうしょう","understanding"]],""],
["順","ジュン","","order; turn; obey",[["順番","じゅんばん","turn"],["順序","じゅんじょ","order"],["順調","じゅんちょう","smooth"]],"逆"],
["岩","ガン","いわ","rock; cliff",[["岩","いわ","rock"],["岩石","がんせき","rock"],["溶岩","ようがん","lava"]],""],
["練","レン","ね.る","practice; train",[["練習","れんしゅう","practice"],["訓練","くんれん","training"],["練る","ねる","to refine"]],""],
["軽","ケイ","かる.い,かろ.やか","light; easy",[["軽い","かるい","light"],["軽量","けいりょう","lightweight"],["手軽","てがる","easy"]],"重"],
// PAGE 4
["了","リョウ","","complete; finish",[["了解","りょうかい","understanding"],["完了","かんりょう","completion"],["終了","しゅうりょう","end"]],""],
["庁","チョウ","","government office",[["庁舎","ちょうしゃ","government building"],["県庁","けんちょう","prefectural office"],["気象庁","きしょうちょう","weather agency"]],""],
["城","ジョウ","しろ","castle",[["城","しろ","castle"],["城下町","じょうかまち","castle town"],["城壁","じょうへき","castle wall"]],""],
["患","カン","わずら.う","afflicted; ill",[["患者","かんじゃ","patient"],["患う","わずらう","to be ill"],["疾患","しっかん","disease"]],""],
["層","ソウ","","layer; stratum",[["層","そう","layer"],["階層","かいそう","social class"],["高層","こうそう","high-rise"]],""],
["版","ハン","","edition; printing",[["出版","しゅっぱん","publishing"],["版画","はんが","woodblock print"],["初版","しょはん","first edition"]],""],
["令","レイ","","order; command",[["命令","めいれい","command"],["法令","ほうれい","law"],["指令","しれい","directive"]],""],
["角","カク","かど,つの","angle; corner; horn",[["角","かど","corner"],["角度","かくど","angle"],["三角","さんかく","triangle"]],""],
["絡","ラク","から.む","entwine; connect",[["連絡","れんらく","contact"],["絡む","からむ","to entwine"],["絡み合う","からみあう","to be entangled"]],""],
["損","ソン","そこ.なう","damage; loss",[["損害","そんがい","damage"],["損する","そんする","to lose"],["破損","はそん","damage"]],"得"],
["募","ボ","つの.る","recruit; collect",[["募集","ぼしゅう","recruitment"],["募金","ぼきん","fundraising"],["応募","おうぼ","application"]],""],
["裏","リ","うら","back; reverse; lining",[["裏","うら","back"],["裏切る","うらぎる","to betray"],["裏側","うらがわ","reverse side"]],"表"],
["仏","ブツ,フツ","ほとけ","Buddha; France",[["仏教","ぶっきょう","Buddhism"],["仏像","ぶつぞう","Buddha statue"],["大仏","だいぶつ","great Buddha"]],""],
["績","セキ","","achievements; results",[["成績","せいせき","grades"],["業績","ぎょうせき","achievements"],["実績","じっせき","track record"]],""],
["築","チク","きず.く","build; construct",[["建築","けんちく","architecture"],["築く","きずく","to build"],["構築","こうちく","construction"]],""],
["貨","カ","","freight; goods; money",[["貨物","かもつ","cargo"],["通貨","つうか","currency"],["雑貨","ざっか","miscellaneous goods"]],""],
["混","コン","ま.じる,こ.む,ま.ぜる","mix; blend",[["混ぜる","まぜる","to mix"],["混雑","こんざつ","congestion"],["混乱","こんらん","confusion"]],""],
["昇","ショウ","のぼ.る","rise; ascend",[["上昇","じょうしょう","rise"],["昇進","しょうしん","promotion"],["昇る","のぼる","to rise"]],"降"],
["池","チ","いけ","pond; pool",[["池","いけ","pond"],["電池","でんち","battery"],["池袋","いけぶくろ","Ikebukuro"]],""],
["血","ケツ","ち","blood",[["血","ち","blood"],["血液","けつえき","blood"],["出血","しゅっけつ","bleeding"]],""],
["温","オン","あたた.かい,あたた.める","warm; temperature",[["温かい","あたたかい","warm"],["温度","おんど","temperature"],["気温","きおん","air temperature"]],"冷"],
["季","キ","","season",[["季節","きせつ","season"],["四季","しき","four seasons"],["季語","きご","seasonal word"]],""],
["星","セイ,ショウ","ほし","star",[["星","ほし","star"],["惑星","わくせい","planet"],["星座","せいざ","constellation"]],""],
["永","エイ","なが.い","eternity; long",[["永遠","えいえん","eternity"],["永久","えいきゅう","permanent"],["永い","ながい","long"]],""],
["著","チョ","いちじる.しい,あらわ.す","author; remarkable",[["著者","ちょしゃ","author"],["著しい","いちじるしい","remarkable"],["著書","ちょしょ","literary work"]],""],
["誌","シ","","magazine; journal",[["雑誌","ざっし","magazine"],["日誌","にっし","journal"],["誌面","しめん","pages of a magazine"]],""],
["庫","コ,ク","くら","storehouse; warehouse",[["倉庫","そうこ","warehouse"],["冷蔵庫","れいぞうこ","refrigerator"],["車庫","しゃこ","garage"]],""],
["刊","カン","","publish; edition",[["刊行","かんこう","publication"],["週刊","しゅうかん","weekly"],["月刊","げっかん","monthly"]],""],
["像","ゾウ","","image; statue",[["想像","そうぞう","imagination"],["映像","えいぞう","image"],["仏像","ぶつぞう","Buddha statue"]],""],
["香","コウ,キョウ","か,かお.り","fragrance; incense",[["香り","かおり","fragrance"],["香水","こうすい","perfume"],["香辛料","こうしんりょう","spice"]],""],
["坂","ハン","さか","slope; hill",[["坂","さか","slope"],["坂道","さかみち","slope road"],["上り坂","のぼりざか","uphill"]],""],
["底","テイ","そこ","bottom; base",[["底","そこ","bottom"],["海底","かいてい","sea floor"],["徹底","てってい","thorough"]],""],
["布","フ","ぬの","cloth; spread",[["布","ぬの","cloth"],["分布","ぶんぷ","distribution"],["毛布","もうふ","blanket"]],""],
["寺","ジ","てら","temple",[["寺","てら","temple"],["寺院","じいん","temple"],["東大寺","とうだいじ","Todai-ji"]],""],
["宇","ウ","","universe; eaves",[["宇宙","うちゅう","space"],["宇宙飛行士","うちゅうひこうし","astronaut"]],""],
["巨","キョ","","giant; huge",[["巨大","きょだい","enormous"],["巨人","きょじん","giant"],["巨額","きょがく","huge amount"]],""],
["震","シン","ふる.う,ふる.える","quake; shake",[["地震","じしん","earthquake"],["震度","しんど","seismic intensity"],["震える","ふるえる","to tremble"]],""],
["希","キ","","hope; rare",[["希望","きぼう","hope"],["希少","きしょう","rare"],["希薄","きはく","thin; dilute"]],""],
["触","ショク","ふ.れる,さわ.る","touch; contact",[["触れる","ふれる","to touch"],["接触","せっしょく","contact"],["感触","かんしょく","feel; texture"]],""],
["依","イ,エ","","depend; rely",[["依頼","いらい","request"],["依存","いぞん","dependence"],["依然","いぜん","still"]],""],
["籍","セキ","","register; membership",[["国籍","こくせき","nationality"],["書籍","しょせき","books"],["戸籍","こせき","family register"]],""],
["汚","オ","よご.す,よご.れる,きたな.い","dirty; pollute",[["汚い","きたない","dirty"],["汚染","おせん","pollution"],["汚れる","よごれる","to get dirty"]],""],
["枚","マイ","","counter for flat things",[["一枚","いちまい","one sheet"],["枚数","まいすう","number of sheets"],["何枚","なんまい","how many sheets"]],""],
["複","フク","","duplicate; complex",[["複雑","ふくざつ","complex"],["複数","ふくすう","plural"],["複製","ふくせい","reproduction"]],"単"],
["郵","ユウ","","mail; postal",[["郵便","ゆうびん","mail"],["郵便局","ゆうびんきょく","post office"],["郵送","ゆうそう","mailing"]],""],
["仲","チュウ","なか","relationship; companion",[["仲間","なかま","companion"],["仲良し","なかよし","close friend"],["仲介","ちゅうかい","mediation"]],""],
["栄","エイ","さか.える","prosper; glory",[["栄える","さかえる","to prosper"],["栄光","えいこう","glory"],["栄養","えいよう","nutrition"]],""],
["札","サツ","ふだ","bill; tag; card",[["札","さつ","bill"],["名札","なふだ","name tag"],["改札","かいさつ","ticket gate"]],""],
["板","ハン,バン","いた","board; plank",[["板","いた","board"],["黒板","こくばん","blackboard"],["看板","かんばん","sign"]],""],
["骨","コツ","ほね","bone",[["骨","ほね","bone"],["骨折","こっせつ","fracture"],["骨格","こっかく","skeleton"]],""],
// PAGE 5
["傾","ケイ","かたむ.く,かたむ.ける","incline; lean",[["傾向","けいこう","tendency"],["傾く","かたむく","to lean"],["傾ける","かたむける","to tilt"]],""],
["届","","とど.く,とど.ける","deliver; reach",[["届ける","とどける","to deliver"],["届く","とどく","to reach"],["届け出","とどけで","notification"]],""],
["巻","カン","ま.く,まき","roll; volume; wind",[["巻く","まく","to wind"],["巻き込む","まきこむ","to involve"],["上巻","じょうかん","first volume"]],""],
["燃","ネン","も.える,も.やす","burn; blaze",[["燃える","もえる","to burn"],["燃料","ねんりょう","fuel"],["燃やす","もやす","to burn"]],""],
["跡","セキ","あと","trace; mark",[["跡","あと","trace"],["足跡","あしあと","footprint"],["遺跡","いせき","ruins"]],""],
["包","ホウ","つつ.む","wrap; pack",[["包む","つつむ","to wrap"],["包装","ほうそう","packaging"],["小包","こづつみ","parcel"]],""],
["駐","チュウ","","stationed; parking",[["駐車場","ちゅうしゃじょう","parking lot"],["駐車","ちゅうしゃ","parking"],["駐在","ちゅうざい","residence"]],""],
["弱","ジャク","よわ.い,よわ.る","weak; feeble",[["弱い","よわい","weak"],["弱点","じゃくてん","weakness"],["弱る","よわる","to weaken"]],"強"],
["紹","ショウ","","introduce",[["紹介","しょうかい","introduction"],["自己紹介","じこしょうかい","self-introduction"]],""],
["雇","コ","やと.う","employ; hire",[["雇う","やとう","to employ"],["雇用","こよう","employment"],["解雇","かいこ","dismissal"]],""],
["替","タイ","か.える,か.わる","exchange; replace",[["両替","りょうがえ","money exchange"],["替える","かえる","to replace"],["交替","こうたい","alternation"]],""],
["預","ヨ","あず.ける,あず.かる","deposit; entrust",[["預ける","あずける","to deposit"],["預金","よきん","deposit"],["預かる","あずかる","to keep"]],""],
["焼","ショウ","や.く,や.ける","burn; bake; grill",[["焼く","やく","to grill"],["焼ける","やける","to burn"],["夕焼け","ゆうやけ","sunset glow"]],""],
["簡","カン","","simple; brief",[["簡単","かんたん","simple"],["簡潔","かんけつ","concise"],["簡略","かんりゃく","brief"]],""],
["章","ショウ","","chapter; badge",[["章","しょう","chapter"],["文章","ぶんしょう","writing"],["勲章","くんしょう","medal"]],""],
["臓","ゾウ","","internal organ",[["心臓","しんぞう","heart"],["内臓","ないぞう","internal organs"],["臓器","ぞうき","organ"]],""],
["律","リツ,リチ","","law; regulation; rhythm",[["法律","ほうりつ","law"],["規律","きりつ","discipline"],["自律","じりつ","autonomy"]],""],
["贈","ゾウ,ソウ","おく.る","give; present",[["贈る","おくる","to give"],["贈り物","おくりもの","gift"],["贈呈","ぞうてい","presentation"]],""],
["照","ショウ","て.る,て.らす","illuminate; shine",[["照らす","てらす","to illuminate"],["参照","さんしょう","reference"],["照明","しょうめい","lighting"]],""],
["薄","ハク","うす.い,うす.める","thin; dilute; pale",[["薄い","うすい","thin"],["薄暗い","うすぐらい","dim"],["軽薄","けいはく","frivolous"]],"厚"],
["群","グン","む.れる,むら","group; flock",[["群れ","むれ","group"],["群衆","ぐんしゅう","crowd"],["群馬","ぐんま","Gunma"]],""],
["秒","ビョウ","","second (time)",[["秒","びょう","second"],["秒速","びょうそく","per second"],["秒針","びょうしん","second hand"]],""],
["奥","オウ","おく","interior; deep",[["奥","おく","interior"],["奥さん","おくさん","wife"],["奥深い","おくぶかい","profound"]],""],
["詰","キツ","つ.める,つ.まる","stuff; cram; packed",[["詰める","つめる","to pack"],["缶詰","かんづめ","canned food"],["行き詰まる","いきづまる","to reach a dead end"]],""],
["双","ソウ","ふた","pair; twin",[["双子","ふたご","twins"],["双方","そうほう","both sides"],["双眼鏡","そうがんきょう","binoculars"]],""],
["刺","シ","さ.す,さ.さる","stab; sting; thorn",[["刺す","さす","to stab"],["名刺","めいし","business card"],["刺激","しげき","stimulus"]],""],
["純","ジュン","","pure; genuine",[["純粋","じゅんすい","pure"],["単純","たんじゅん","simple"],["純真","じゅんしん","innocent"]],""],
["翌","ヨク","","the following; next",[["翌日","よくじつ","next day"],["翌年","よくねん","next year"],["翌朝","よくあさ","next morning"]],""],
["快","カイ","こころよ.い","cheerful; pleasant",[["快適","かいてき","comfortable"],["愉快","ゆかい","pleasant"],["快い","こころよい","pleasant"]],"不快"],
["片","ヘン","かた","fragment; one-sided",[["片方","かたほう","one side"],["破片","はへん","fragment"],["片付ける","かたづける","to tidy up"]],""],
["敬","ケイ","うやま.う","respect; honor",[["敬語","けいご","polite language"],["敬う","うやまう","to respect"],["尊敬","そんけい","respect"]],""],
["悩","ノウ","なや.む,なや.ます","worry; distress",[["悩む","なやむ","to worry"],["悩み","なやみ","worry"],["悩ます","なやます","to trouble"]],""],
["泉","セン","いずみ","spring; fountain",[["泉","いずみ","spring"],["温泉","おんせん","hot spring"],["源泉","げんせん","source"]],""],
["皮","ヒ","かわ","skin; hide; leather",[["皮","かわ","skin"],["皮膚","ひふ","skin"],["毛皮","けがわ","fur"]],""],
["漁","ギョ,リョウ","","fishing",[["漁業","ぎょぎょう","fishing industry"],["漁師","りょうし","fisherman"],["漁船","ぎょせん","fishing boat"]],""],
["荒","コウ","あら.い,あ.れる","rough; wild; waste",[["荒い","あらい","rough"],["荒れる","あれる","to become rough"],["荒野","こうや","wasteland"]],""],
["貯","チョ","た.める","savings; store",[["貯金","ちょきん","savings"],["貯蓄","ちょちく","savings"],["貯める","ためる","to save up"]],""],
["硬","コウ","かた.い","hard; stiff",[["硬い","かたい","hard"],["硬貨","こうか","coin"],["硬直","こうちょく","rigidity"]],"軟"],
["埋","マイ","う.める,う.まる","bury; fill up",[["埋める","うめる","to bury"],["埋まる","うまる","to be buried"],["埋葬","まいそう","burial"]],""],
["柱","チュウ","はしら","pillar; column",[["柱","はしら","pillar"],["電柱","でんちゅう","telephone pole"],["大黒柱","だいこくばしら","main pillar"]],""],
["祭","サイ","まつ.り,まつ.る","festival; worship",[["祭り","まつり","festival"],["文化祭","ぶんかさい","culture festival"],["祭日","さいじつ","holiday"]],""],
["袋","タイ","ふくろ","bag; sack",[["袋","ふくろ","bag"],["紙袋","かみぶくろ","paper bag"],["手袋","てぶくろ","gloves"]],""],
["筆","ヒツ","ふで","brush; writing",[["筆","ふで","brush"],["筆者","ひっしゃ","author"],["鉛筆","えんぴつ","pencil"]],""],
["訓","クン","","instruction; Japanese reading",[["訓練","くんれん","training"],["訓読み","くんよみ","kun reading"],["教訓","きょうくん","lesson"]],""],
["浴","ヨク","あ.びる","bathe; bask in",[["入浴","にゅうよく","bathing"],["浴びる","あびる","to bathe"],["浴室","よくしつ","bathroom"]],""],
["童","ドウ","わらべ","child",[["児童","じどう","children"],["童話","どうわ","fairy tale"],["童謡","どうよう","nursery rhyme"]],""],
["宝","ホウ","たから","treasure",[["宝","たから","treasure"],["宝石","ほうせき","jewel"],["宝物","たからもの","treasure"]],""],
["封","フウ,ホウ","","seal; blockade",[["封筒","ふうとう","envelope"],["封鎖","ふうさ","blockade"],["封建","ほうけん","feudal"]],""],
["胸","キョウ","むね","chest; breast",[["胸","むね","chest"],["胸囲","きょうい","chest measurement"],["度胸","どきょう","courage"]],""],
["砂","サ,シャ","すな","sand",[["砂","すな","sand"],["砂漠","さばく","desert"],["砂糖","さとう","sugar"]],""],
// PAGE 6
["塩","エン","しお","salt",[["塩","しお","salt"],["塩分","えんぶん","salt content"],["塩辛い","しおからい","salty"]],""],
["賢","ケン","かしこ.い","wise; clever",[["賢い","かしこい","clever"],["賢明","けんめい","wise"],["賢者","けんじゃ","wise person"]],""],
["腕","ワン","うで","arm; skill",[["腕","うで","arm"],["腕前","うでまえ","skill"],["腕時計","うでどけい","wristwatch"]],""],
["兆","チョウ","きざ.す","trillion; omen",[["兆","ちょう","trillion"],["兆候","ちょうこう","sign"],["前兆","ぜんちょう","omen"]],""],
["床","ショウ","とこ,ゆか","floor; bed",[["床","ゆか","floor"],["床屋","とこや","barber"],["起床","きしょう","rising"]],""],
["毛","モウ","け","hair; fur; wool",[["毛","け","hair"],["毛布","もうふ","blanket"],["羊毛","ようもう","wool"]],""],
["緑","リョク,ロク","みどり","green",[["緑","みどり","green"],["緑色","みどりいろ","green color"],["緑茶","りょくちゃ","green tea"]],""],
["尊","ソン","たっと.い,とうと.い,たっと.ぶ","respect; revere",[["尊敬","そんけい","respect"],["尊い","とうとい","precious"],["尊重","そんちょう","respect"]],""],
["祝","シュク,シュウ","いわ.う","celebrate; congratulate",[["祝う","いわう","to celebrate"],["祝日","しゅくじつ","holiday"],["お祝い","おいわい","celebration"]],""],
["柔","ジュウ,ニュウ","やわ.らかい","soft; gentle; flexible",[["柔らかい","やわらかい","soft"],["柔道","じゅうどう","judo"],["柔軟","じゅうなん","flexible"]],""],
["殿","デン,テン","との,どの","palace; lord; Mr.",[["殿様","とのさま","lord"],["宮殿","きゅうでん","palace"],["殿","どの","Mr./Ms."]],""],
["濃","ノウ","こ.い","thick; concentrated; dark",[["濃い","こい","thick; dark"],["濃度","のうど","concentration"],["濃厚","のうこう","rich; thick"]],"薄"],
["液","エキ","","liquid; fluid",[["液体","えきたい","liquid"],["血液","けつえき","blood"],["液晶","えきしょう","liquid crystal"]],""],
["衣","イ","ころも,きぬ","clothes; garment",[["衣服","いふく","clothing"],["衣類","いるい","clothing"],["浴衣","ゆかた","yukata"]],""],
["肩","ケン","かた","shoulder",[["肩","かた","shoulder"],["肩書き","かたがき","title"],["肩こり","かたこり","stiff shoulders"]],""],
["零","レイ","","zero",[["零","れい","zero"],["零点","れいてん","zero points"],["零下","れいか","below zero"]],""],
["幼","ヨウ","おさな.い","infancy; childhood",[["幼い","おさない","young"],["幼児","ようじ","infant"],["幼稚園","ようちえん","kindergarten"]],""],
["荷","カ","に","luggage; load; cargo",[["荷物","にもつ","luggage"],["荷","に","load"],["出荷","しゅっか","shipment"]],""],
["泊","ハク","と.まる,と.める","stay overnight",[["泊まる","とまる","to stay"],["一泊","いっぱく","one night stay"],["宿泊","しゅくはく","accommodation"]],""],
["黄","コウ,オウ","き,こ","yellow",[["黄色","きいろ","yellow"],["黄金","おうごん","gold"],["黄葉","こうよう","yellow leaves"]],""],
["甘","カン","あま.い,あま.える","sweet; indulgent",[["甘い","あまい","sweet"],["甘える","あまえる","to depend on"],["甘口","あまくち","sweet taste"]],"辛"],
["臣","シン,ジン","","subject; retainer",[["大臣","だいじん","minister"],["臣下","しんか","retainer"],["家臣","かしん","vassal"]],""],
["浅","セン","あさ.い","shallow; superficial",[["浅い","あさい","shallow"],["浅草","あさくさ","Asakusa"],["浅瀬","あさせ","shallow water"]],"深"],
["掃","ソウ","は.く","sweep; clean",[["掃除","そうじ","cleaning"],["掃く","はく","to sweep"],["清掃","せいそう","cleaning"]],""],
["雲","ウン","くも","cloud",[["雲","くも","cloud"],["入道雲","にゅうどうぐも","thundercloud"],["雲海","うんかい","sea of clouds"]],""],
["掘","クツ","ほ.る","dig; excavate",[["掘る","ほる","to dig"],["発掘","はっくつ","excavation"],["採掘","さいくつ","mining"]],""],
["捨","シャ","す.てる","discard; throw away",[["捨てる","すてる","to throw away"],["四捨五入","ししゃごにゅう","rounding"]],"拾"],
["軟","ナン","やわ.らかい","soft; flexible",[["軟らかい","やわらかい","soft"],["軟弱","なんじゃく","weak"],["柔軟","じゅうなん","flexible"]],"硬"],
["沈","チン","しず.む,しず.める","sink; submerge",[["沈む","しずむ","to sink"],["沈黙","ちんもく","silence"],["沈没","ちんぼつ","sinking"]],"浮"],
["凍","トウ","こお.る,こご.える","freeze",[["凍る","こおる","to freeze"],["冷凍","れいとう","freezing"],["凍える","こごえる","to be frozen"]],""],
["乳","ニュウ","ちち,ち","milk; breast",[["牛乳","ぎゅうにゅう","milk"],["乳","ちち","breast"],["乳製品","にゅうせいひん","dairy products"]],""],
["恋","レン","こ.い,こい.しい","love; romance",[["恋","こい","love"],["恋人","こいびと","lover"],["恋愛","れんあい","romance"]],""],
["紅","コウ,ク","べに,くれない","crimson; rouge",[["紅茶","こうちゃ","black tea"],["口紅","くちべに","lipstick"],["紅葉","こうよう","autumn leaves"]],""],
["郊","コウ","","suburb; outskirts",[["郊外","こうがい","suburbs"],["近郊","きんこう","outskirts"]],""],
["腰","ヨウ","こし","waist; hips",[["腰","こし","waist"],["腰掛ける","こしかける","to sit down"],["弱腰","よわごし","weak attitude"]],""],
["炭","タン","すみ","charcoal; coal; carbon",[["炭","すみ","charcoal"],["石炭","せきたん","coal"],["炭素","たんそ","carbon"]],""],
["踊","ヨウ","おど.る","dance",[["踊る","おどる","to dance"],["踊り","おどり","dance"],["盆踊り","ぼんおどり","Bon dance"]],""],
["冊","サツ,サク","","volume; counter for books",[["一冊","いっさつ","one volume"],["冊子","さっし","booklet"],["別冊","べっさつ","extra issue"]],""],
["勇","ユウ","いさ.む","courage; bravery",[["勇気","ゆうき","courage"],["勇ましい","いさましい","brave"],["勇敢","ゆうかん","courageous"]],""],
["械","カイ","","machine; instrument",[["機械","きかい","machine"],["器械","きかい","apparatus"]],""],
["菜","サイ","な","vegetable; greens",[["野菜","やさい","vegetable"],["菜食","さいしょく","vegetarian"],["菜の花","なのはな","canola flower"]],""],
["珍","チン","めずら.しい","rare; curious",[["珍しい","めずらしい","rare"],["珍味","ちんみ","delicacy"],["珍品","ちんぴん","rarity"]],""],
["卵","ラン","たまご","egg",[["卵","たまご","egg"],["卵焼き","たまごやき","omelet"],["産卵","さんらん","egg-laying"]],""],
["湖","コ","みずうみ","lake",[["湖","みずうみ","lake"],["湖畔","こはん","lakeside"],["琵琶湖","びわこ","Lake Biwa"]],""],
["喫","キツ","","consume; eat; drink; smoke",[["喫茶店","きっさてん","cafe"],["喫煙","きつえん","smoking"],["喫茶","きっさ","tea drinking"]],""],
["干","カン","ほ.す,ひ.る","dry; drought",[["干す","ほす","to dry"],["干ばつ","かんばつ","drought"],["干潮","かんちょう","low tide"]],""],
["虫","チュウ","むし","insect; bug",[["虫","むし","insect"],["昆虫","こんちゅう","insect"],["虫歯","むしば","cavity"]],""],
["刷","サツ","す.る","print",[["印刷","いんさつ","printing"],["刷る","する","to print"],["増刷","ぞうさつ","reprinting"]],""],
["湯","トウ","ゆ","hot water; bath",[["湯","ゆ","hot water"],["銭湯","せんとう","public bath"],["湯気","ゆげ","steam"]],""],
["溶","ヨウ","と.ける,と.かす","dissolve; melt",[["溶ける","とける","to dissolve"],["溶かす","とかす","to melt"],["溶岩","ようがん","lava"]],""],
// PAGE 7
["鉱","コウ","","mineral; ore",[["鉱物","こうぶつ","mineral"],["鉱山","こうざん","mine"],["鉱石","こうせき","ore"]],""],
["涙","ルイ","なみだ","tears; cry",[["涙","なみだ","tears"],["涙ぐむ","なみだぐむ","to be tearful"],["感涙","かんるい","tears of emotion"]],""],
["匹","ヒキ","","counter for animals",[["一匹","いっぴき","one animal"],["匹敵","ひってき","equal to"]],""],
["孫","ソン","まご","grandchild",[["孫","まご","grandchild"],["子孫","しそん","descendants"],["孫娘","まごむすめ","granddaughter"]],""],
["鋭","エイ","するど.い","sharp; keen",[["鋭い","するどい","sharp"],["鋭角","えいかく","acute angle"],["鋭敏","えいびん","keen"]],"鈍"],
["枝","シ","えだ","branch; twig",[["枝","えだ","branch"],["枝豆","えだまめ","edamame"],["小枝","こえだ","twig"]],""],
["塗","ト","ぬ.る","paint; plaster",[["塗る","ぬる","to paint"],["塗料","とりょう","paint"],["塗装","とそう","coating"]],""],
["軒","ケン","のき","eaves; counter for houses",[["軒","のき","eaves"],["一軒","いっけん","one house"],["軒先","のきさき","edge of eaves"]],""],
["毒","ドク","","poison; toxin",[["毒","どく","poison"],["中毒","ちゅうどく","poisoning"],["毒薬","どくやく","poison"]],""],
["叫","キョウ","さけ.ぶ","shout; cry",[["叫ぶ","さけぶ","to shout"],["叫び","さけび","shout"],["絶叫","ぜっきょう","scream"]],""],
["拝","ハイ","おが.む","worship; bow",[["拝む","おがむ","to worship"],["参拝","さんぱい","worship"],["拝見","はいけん","viewing (humble)"]],""],
["氷","ヒョウ","こおり,ひ","ice",[["氷","こおり","ice"],["氷山","ひょうざん","iceberg"],["氷河","ひょうが","glacier"]],""],
["乾","カン","かわ.く,かわ.かす","dry; parch",[["乾く","かわく","to dry"],["乾燥","かんそう","dryness"],["乾杯","かんぱい","cheers"]],"湿"],
["棒","ボウ","","stick; rod; bar",[["棒","ぼう","stick"],["鉄棒","てつぼう","iron bar"],["棒グラフ","ぼうグラフ","bar graph"]],""],
["祈","キ","いの.る","pray; wish",[["祈る","いのる","to pray"],["祈り","いのり","prayer"],["祈願","きがん","prayer"]],""],
["拾","シュウ,ジュウ","ひろ.う","pick up; gather; ten",[["拾う","ひろう","to pick up"],["拾得","しゅうとく","finding"],["拾い物","ひろいもの","a find"]],"捨"],
["粉","フン","こ,こな","powder; flour",[["粉","こな","powder"],["小麦粉","こむぎこ","flour"],["花粉","かふん","pollen"]],""],
["糸","シ","いと","thread; string",[["糸","いと","thread"],["毛糸","けいと","yarn"],["糸口","いとぐち","clue"]],""],
["綿","メン","わた","cotton; cotton wool",[["綿","わた","cotton"],["綿密","めんみつ","meticulous"],["木綿","もめん","cotton"]],""],
["汗","カン","あせ","sweat; perspiration",[["汗","あせ","sweat"],["冷や汗","ひやあせ","cold sweat"],["発汗","はっかん","sweating"]],""],
["銅","ドウ","","copper; bronze",[["銅","どう","copper"],["青銅","せいどう","bronze"],["銅メダル","どうメダル","bronze medal"]],""],
["湿","シツ","しめ.る,しめ.す","damp; moist",[["湿気","しっけ","humidity"],["湿度","しつど","humidity"],["湿る","しめる","to be damp"]],"乾"],
["瓶","ビン","","bottle; jar",[["瓶","びん","bottle"],["花瓶","かびん","vase"],["空き瓶","あきびん","empty bottle"]],""],
["咲","","さ.く","bloom; blossom",[["咲く","さく","to bloom"],["咲き誇る","さきほこる","to bloom in full"]],""],
["召","ショウ","め.す","summon; wear; eat",[["召し上がる","めしあがる","to eat (honorific)"],["召す","めす","to summon"],["召集","しょうしゅう","convocation"]],""],
["缶","カン","","can; tin",[["缶","かん","can"],["缶詰","かんづめ","canned food"],["空き缶","あきかん","empty can"]],""],
["隻","セキ","","counter for ships",[["一隻","いっせき","one ship"],["隻眼","せきがん","one eye"]],""],
["脂","シ","あぶら","fat; grease",[["脂肪","しぼう","fat"],["脂","あぶら","fat"],["皮脂","ひし","sebum"]],""],
["蒸","ジョウ","む.す,む.れる,む.らす","steam; evaporate",[["蒸す","むす","to steam"],["蒸気","じょうき","steam"],["蒸発","じょうはつ","evaporation"]],""],
["肌","キ","はだ","skin; texture",[["肌","はだ","skin"],["肌着","はだぎ","underwear"],["鳥肌","とりはだ","goosebumps"]],""],
["耕","コウ","たがや.す","cultivate; plow",[["耕す","たがやす","to cultivate"],["耕地","こうち","farmland"],["農耕","のうこう","farming"]],""],
["鈍","ドン","にぶ.い,にぶ.る","dull; blunt; slow",[["鈍い","にぶい","dull"],["鈍感","どんかん","insensitive"],["鈍る","にぶる","to become dull"]],"鋭"],
["泥","デイ","どろ","mud; dirt",[["泥","どろ","mud"],["泥棒","どろぼう","thief"],["泥沼","どろぬま","quagmire"]],""],
["隅","グウ","すみ","corner; nook",[["隅","すみ","corner"],["片隅","かたすみ","corner"],["隅々","すみずみ","every corner"]],""],
["灯","トウ","ひ","lamp; light",[["電灯","でんとう","electric light"],["灯台","とうだい","lighthouse"],["灯り","あかり","light"]],""],
["辛","シン","から.い,つら.い","spicy; hot; harsh",[["辛い","からい","spicy"],["辛い","つらい","harsh"],["辛抱","しんぼう","patience"]],"甘"],
["磨","マ","みが.く","polish; grind",[["磨く","みがく","to polish"],["歯磨き","はみがき","tooth brushing"],["研磨","けんま","polishing"]],""],
["麦","バク","むぎ","wheat; barley",[["麦","むぎ","wheat"],["小麦","こむぎ","wheat"],["麦茶","むぎちゃ","barley tea"]],""],
["姓","セイ,ショウ","","surname; family name",[["姓","せい","surname"],["姓名","せいめい","full name"],["旧姓","きゅうせい","maiden name"]],""],
["筒","トウ","つつ","cylinder; tube",[["封筒","ふうとう","envelope"],["筒","つつ","tube"],["水筒","すいとう","water bottle"]],""],
["鼻","ビ","はな","nose",[["鼻","はな","nose"],["鼻水","はなみず","runny nose"],["鼻血","はなぢ","nosebleed"]],""],
["粒","リュウ","つぶ","grain; drop",[["粒","つぶ","grain"],["米粒","こめつぶ","grain of rice"],["粒子","りゅうし","particle"]],""],
["詞","シ","","word; part of speech",[["歌詞","かし","lyrics"],["名詞","めいし","noun"],["動詞","どうし","verb"]],""],
["胃","イ","","stomach",[["胃","い","stomach"],["胃腸","いちょう","stomach and intestines"],["胃痛","いつう","stomachache"]],""],
["畳","ジョウ","たたみ,たた.む","tatami mat; fold",[["畳","たたみ","tatami"],["畳む","たたむ","to fold"],["四畳半","よじょうはん","4.5 tatami room"]],""],
["机","キ","つくえ","desk; table",[["机","つくえ","desk"],["机上","きじょう","on the desk"],["事務机","じむづくえ","office desk"]],""],
["膚","フ","","skin",[["皮膚","ひふ","skin"],["皮膚科","ひふか","dermatology"]],""],
["濯","タク","","wash; rinse",[["洗濯","せんたく","laundry"],["洗濯機","せんたくき","washing machine"]],""],
["塔","トウ","","tower; pagoda",[["塔","とう","tower"],["東京タワー","とうきょうタワー","Tokyo Tower"],["五重塔","ごじゅうのとう","five-story pagoda"]],""],
["沸","フツ","わ.く,わ.かす","boil; seethe",[["沸かす","わかす","to boil"],["沸く","わく","to boil"],["沸騰","ふっとう","boiling"]],""],
// PAGE 8
["灰","カイ","はい","ash; gray",[["灰","はい","ash"],["灰色","はいいろ","gray"],["火山灰","かざんばい","volcanic ash"]],""],
["菓","カ","","confection; candy",[["菓子","かし","sweets"],["和菓子","わがし","Japanese sweets"],["洋菓子","ようがし","Western sweets"]],""],
["帽","ボウ","","hat; cap",[["帽子","ぼうし","hat"],["脱帽","だつぼう","removing hat"]],""],
["枯","コ","か.れる,か.らす","wither; dry up",[["枯れる","かれる","to wither"],["枯葉","かれは","dead leaf"],["枯れ木","かれき","dead tree"]],""],
["涼","リョウ","すず.しい,すず.む","cool; refreshing",[["涼しい","すずしい","cool"],["涼む","すずむ","to cool off"],["清涼","せいりょう","refreshing"]],"暑"],
["舟","シュウ","ふね,ふな","boat; ship",[["舟","ふね","boat"],["小舟","こぶね","small boat"],["舟歌","ふなうた","boatman's song"]],""],
["貝","バイ","かい","shellfish",[["貝","かい","shellfish"],["貝殻","かいがら","seashell"],["巻き貝","まきがい","snail"]],""],
["符","フ","","sign; mark; talisman",[["切符","きっぷ","ticket"],["符号","ふごう","symbol"],["音符","おんぷ","musical note"]],""],
["憎","ゾウ","にく.む,にく.い","hate; detest",[["憎む","にくむ","to hate"],["憎い","にくい","hateful"],["憎しみ","にくしみ","hatred"]],""],
["皿","","さら","dish; plate",[["皿","さら","plate"],["灰皿","はいざら","ashtray"],["小皿","こざら","small plate"]],""],
["肯","コウ","","agree; consent",[["肯定","こうてい","affirmation"],["肯定的","こうていてき","positive"]],"否"],
["燥","ソウ","","dry; parch",[["乾燥","かんそう","dryness"],["乾燥機","かんそうき","dryer"]],""],
["畜","チク","","livestock; domestic animal",[["家畜","かちく","livestock"],["畜産","ちくさん","livestock industry"],["牧畜","ぼくちく","stock farming"]],""],
["挟","キョウ","はさ.む,はさ.まる","pinch; insert between",[["挟む","はさむ","to insert"],["板挟み","いたばさみ","dilemma"],["挟まる","はさまる","to be caught"]],""],
["曇","ドン","くも.る","cloudy; overcast",[["曇り","くもり","cloudy"],["曇る","くもる","to become cloudy"],["曇天","どんてん","cloudy sky"]],"晴"],
["滴","テキ","しずく","drop; drip",[["滴","しずく","drop"],["水滴","すいてき","water drop"],["雨滴","うてき","raindrop"]],""],
["伺","シ","うかが.う","visit; ask; inquire (humble)",[["伺う","うかがう","to visit (humble)"],["お伺い","おうかがい","inquiry"]],""],
// END OF DATA
];

// Convert compact format to full format
function toKanjiJS(arr) {
  return arr.map(([kanji, onStr, kunStr, meaning, compounds, antonym]) => {
    const on = onStr ? onStr.split(',') : [];
    const kun = kunStr ? kunStr.split(',') : [];
    const comps = compounds.map(([word, reading, m]) => `{word:"${word}",reading:"${reading}",meaning:"${m}"}`).join(',');
    const ant = antonym ? `"${antonym}"` : 'null';
    return `  { kanji:"${kanji}", on:[${on.map(r=>`"${r}"`).join(',')}], kun:[${kun.map(r=>`"${r}"`).join(',')}], meaning:"${meaning}", compounds:[${comps}], antonym:${ant} }`;
  }).join(',\n');
}

// Read n4.html as template
const template = fs.readFileSync(path.join(__dirname, 'n4.html'), 'utf8');

// Build the kanji data string
const kanjiDataStr = toKanjiJS(DATA);
const total = DATA.length;

let output = template;

// Replace title
output = output.replace('<title>JLPT N4 Practice</title>', '<title>JLPT N2 Practice</title>');

// Replace logo
output = output.replace('JLPT <span>N4</span>', 'JLPT <span>N2</span>');

// Replace stats bar /166
output = output.replace('/166</div>', `/${total}</div>`);

// Replace KANJI DATA comment
output = output.replace('All 166 JLPT N4 Kanji', `All ${total} JLPT N2 Kanji`);

// Replace TOTAL
output = output.replace('const TOTAL = 166;', `const TOTAL = ${total};`);

// Replace the KANJI array (bracket-counting to handle single-line arrays)
const kanji_start = output.match(/const KANJI\s*=\s*\[/);
if (kanji_start) {
  const si = kanji_start.index;
  const bi = si + kanji_start[0].length - 1;
  let depth = 1, ei = bi + 1;
  while (depth > 0 && ei < output.length) {
    if (output[ei] === '[') depth++;
    else if (output[ei] === ']') depth--;
    ei++;
  }
  // ei now points past the closing ], find the semicolon
  while (ei < output.length && output[ei] !== ';') ei++;
  output = output.substring(0, si) + `const KANJI = [\n${kanjiDataStr}\n];` + output.substring(ei + 1);
}

// Replace localStorage key
output = output.replace(/jlpt_n4/g, 'jlpt_n2');

// Replace review header
output = output.replace('All 166 Kanji — JLPT N4', `All ${total} Kanji — JLPT N2`);

// Replace filter button
output = output.replace('All (166)', `All (${total})`);

// Replace settings "All" option
output = output.replace('<option value="166">All 166</option>', `<option value="${total}">All ${total}</option>`);

// Replace default kanji display
output = output.replace('>会</div>', '>党</div>');

fs.writeFileSync(path.join(__dirname, 'n2.html'), output, 'utf8');
console.log(`Generated n2.html with ${total} kanji entries.`);
