// Radical → Kanji mapping data
// Each radical has: num, rad, variants, jpName, meaning, kanji [{char, meaning}]
const DATA = [
{num:1,rad:"一",v:[],jp:"いち",m:"one",k:[{c:"一",m:"one"},{c:"不",m:"negative"},{c:"上",m:"above"},{c:"下",m:"below"},{c:"世",m:"generation"},{c:"丈",m:"length"},{c:"三",m:"three"},{c:"万",m:"ten thousand"},{c:"与",m:"bestow"},{c:"両",m:"both"},{c:"七",m:"seven"},{c:"並",m:"row"},{c:"丁",m:"street"},{c:"丘",m:"hill"},{c:"丞",m:"help"},{c:"丙",m:"third class"},{c:"且",m:"moreover"},{c:"丑",m:"ox"}]},
{num:2,rad:"丨",v:[],jp:"ぼう",m:"line",k:[{c:"中",m:"in/middle"},{c:"串",m:"spit/skewer"}]},
{num:3,rad:"丶",v:[],jp:"てん",m:"dot",k:[{c:"主",m:"lord"},{c:"丸",m:"round"},{c:"丹",m:"rust-colored"},{c:"丼",m:"bowl"}]},
{num:4,rad:"丿",v:[],jp:"の",m:"bend",k:[{c:"乗",m:"ride"},{c:"之",m:"of"},{c:"久",m:"long time"},{c:"乏",m:"destitution"},{c:"乃",m:"from"}]},
{num:5,rad:"乙",v:["乚"],jp:"おつ",m:"second",k:[{c:"乱",m:"riot"},{c:"九",m:"nine"},{c:"乾",m:"drought"},{c:"乙",m:"the latter"},{c:"乳",m:"milk"},{c:"亀",m:"tortoise"},{c:"乞",m:"beg"},{c:"也",m:"to be"}]},
{num:6,rad:"亅",v:[],jp:"はねぼう",m:"hook",k:[{c:"事",m:"matter"},{c:"了",m:"complete"},{c:"予",m:"beforehand"},{c:"争",m:"contend"}]},
{num:7,rad:"二",v:[],jp:"ふた",m:"two",k:[{c:"二",m:"two"},{c:"五",m:"five"},{c:"互",m:"mutually"},{c:"井",m:"well"},{c:"亜",m:"Asia"},{c:"亘",m:"span"}]},
{num:8,rad:"亠",v:[],jp:"なべぶた",m:"lid",k:[{c:"交",m:"mingle"},{c:"亡",m:"deceased"},{c:"京",m:"capital"},{c:"亭",m:"pavilion"},{c:"亥",m:"sign of hog"},{c:"享",m:"enjoy"},{c:"亮",m:"clear"},{c:"亦",m:"also"},{c:"亨",m:"pass through"}]},
{num:9,rad:"人",v:["亻"],jp:"ひと",m:"human",k:[{c:"人",m:"person"},{c:"何",m:"what"},{c:"今",m:"now"},{c:"会",m:"meeting"},{c:"体",m:"body"},{c:"作",m:"make"},{c:"使",m:"use"},{c:"信",m:"faith"},{c:"代",m:"substitute"},{c:"仕",m:"attend"},{c:"他",m:"other"},{c:"付",m:"adhere"},{c:"任",m:"responsibility"},{c:"伝",m:"transmit"},{c:"件",m:"affair"},{c:"休",m:"rest"},{c:"供",m:"submit"},{c:"保",m:"protect"},{c:"住",m:"dwell"},{c:"修",m:"discipline"},{c:"例",m:"example"},{c:"借",m:"borrow"},{c:"便",m:"convenience"},{c:"値",m:"price"},{c:"働",m:"work"},{c:"低",m:"lower"},{c:"位",m:"rank"},{c:"似",m:"becoming"},{c:"倒",m:"overthrow"},{c:"優",m:"tenderness"}]},
{num:10,rad:"儿",v:[],jp:"にんにょう",m:"legs",k:[{c:"元",m:"beginning"},{c:"先",m:"before"},{c:"光",m:"light"},{c:"児",m:"newborn"},{c:"兄",m:"elder brother"},{c:"充",m:"allot"},{c:"免",m:"excuse"},{c:"兆",m:"portent"},{c:"克",m:"overcome"}]},
{num:11,rad:"入",v:[],jp:"いる",m:"enter",k:[{c:"入",m:"enter"},{c:"全",m:"whole"},{c:"内",m:"inside"}]},
{num:12,rad:"八",v:[],jp:"はちがしら",m:"divide",k:[{c:"八",m:"eight"},{c:"六",m:"six"},{c:"公",m:"public"},{c:"共",m:"together"},{c:"兵",m:"soldier"},{c:"具",m:"tool"},{c:"典",m:"code"},{c:"分",m:"part"}]},
{num:13,rad:"冂",v:[],jp:"まきがまえ",m:"upside down box",k:[{c:"内",m:"inside"},{c:"円",m:"circle"},{c:"冊",m:"volume"},{c:"再",m:"again"}]},
{num:14,rad:"冖",v:[],jp:"わかんむり",m:"cover",k:[{c:"写",m:"copy"},{c:"冗",m:"superfluous"},{c:"冠",m:"crown"},{c:"軍",m:"army"},{c:"冥",m:"dark"}]},
{num:15,rad:"冫",v:[],jp:"にすい",m:"ice",k:[{c:"冬",m:"winter"},{c:"冷",m:"cool"},{c:"凍",m:"frozen"},{c:"凄",m:"uncanny"},{c:"准",m:"quasi"},{c:"凝",m:"congeal"},{c:"凛",m:"cold"},{c:"次",m:"next"},{c:"冶",m:"melting"}]},
{num:16,rad:"几",v:[],jp:"つくえ",m:"table",k:[{c:"机",m:"desk"},{c:"凡",m:"mediocre"},{c:"凧",m:"kite"},{c:"風",m:"wind"}]},
{num:17,rad:"凵",v:[],jp:"うけばこ",m:"container",k:[{c:"出",m:"exit"},{c:"凶",m:"villain"},{c:"凹",m:"concave"},{c:"凸",m:"convex"},{c:"函",m:"box"}]},
{num:18,rad:"刀",v:["刂"],jp:"かたな",m:"knife",k:[{c:"刀",m:"sword"},{c:"切",m:"cut"},{c:"分",m:"part"},{c:"初",m:"first"},{c:"別",m:"separate"},{c:"利",m:"profit"},{c:"判",m:"judgment"},{c:"制",m:"system"},{c:"刊",m:"publish"},{c:"前",m:"before"},{c:"削",m:"plane"},{c:"割",m:"proportion"},{c:"刻",m:"engrave"},{c:"則",m:"rule"},{c:"副",m:"vice-"},{c:"剣",m:"sword"},{c:"劇",m:"drama"},{c:"刑",m:"punish"},{c:"列",m:"row"},{c:"創",m:"genesis"}]},
{num:19,rad:"力",v:[],jp:"ちから",m:"power",k:[{c:"力",m:"power"},{c:"動",m:"move"},{c:"助",m:"help"},{c:"努",m:"toil"},{c:"効",m:"merit"},{c:"勉",m:"exertion"},{c:"勝",m:"win"},{c:"勢",m:"forces"},{c:"務",m:"task"},{c:"勤",m:"diligence"},{c:"加",m:"add"},{c:"募",m:"recruit"},{c:"勇",m:"courage"},{c:"劣",m:"inferiority"},{c:"功",m:"achievement"}]},
{num:20,rad:"勹",v:[],jp:"つつみがまえ",m:"wrap",k:[{c:"包",m:"wrap"},{c:"勾",m:"hook"},{c:"匂",m:"smell"},{c:"勿",m:"not"},{c:"匁",m:"monme"}]},
{num:21,rad:"匕",v:[],jp:"さじのひ",m:"spoon",k:[{c:"化",m:"change"},{c:"北",m:"north"},{c:"匙",m:"spoon"}]},
{num:22,rad:"匚",v:[],jp:"はこがまえ",m:"box",k:[{c:"区",m:"ward"},{c:"医",m:"doctor"},{c:"匠",m:"artisan"},{c:"匿",m:"hide"}]},
{num:23,rad:"匸",v:[],jp:"かくしがまえ",m:"hiding enclosure",k:[{c:"匹",m:"equal"}]},
{num:24,rad:"十",v:[],jp:"じゅう",m:"ten",k:[{c:"十",m:"ten"},{c:"千",m:"thousand"},{c:"半",m:"half"},{c:"南",m:"south"},{c:"卒",m:"graduate"},{c:"協",m:"cooperate"},{c:"博",m:"doctor"},{c:"午",m:"noon"},{c:"卓",m:"eminent"},{c:"升",m:"measuring box"},{c:"華",m:"splendor"}]},
{num:25,rad:"卜",v:[],jp:"ぼくのと",m:"divination",k:[{c:"占",m:"fortune-telling"},{c:"卜",m:"divination"},{c:"上",m:"above"}]},
{num:26,rad:"卩",v:["㔾"],jp:"ふしづくり",m:"seal",k:[{c:"印",m:"stamp"},{c:"即",m:"instant"},{c:"却",m:"instead"},{c:"卵",m:"egg"},{c:"危",m:"dangerous"}]},
{num:27,rad:"厂",v:[],jp:"がんだれ",m:"cliff",k:[{c:"原",m:"meadow"},{c:"厚",m:"thick"},{c:"厳",m:"stern"},{c:"圧",m:"pressure"},{c:"厄",m:"unlucky"}]},
{num:28,rad:"厶",v:[],jp:"む",m:"private",k:[{c:"私",m:"private"},{c:"去",m:"gone"},{c:"台",m:"pedestal"},{c:"参",m:"participate"},{c:"県",m:"prefecture"},{c:"能",m:"ability"},{c:"厶",m:"private"}]},
{num:29,rad:"又",v:[],jp:"また",m:"right hand",k:[{c:"又",m:"again"},{c:"友",m:"friend"},{c:"反",m:"anti-"},{c:"取",m:"take"},{c:"受",m:"receive"},{c:"収",m:"income"},{c:"双",m:"pair"},{c:"叔",m:"uncle"},{c:"及",m:"reach"},{c:"叙",m:"confer"}]},
{num:30,rad:"口",v:[],jp:"くち",m:"mouth",k:[{c:"口",m:"mouth"},{c:"右",m:"right"},{c:"名",m:"name"},{c:"古",m:"old"},{c:"号",m:"number"},{c:"合",m:"fit"},{c:"同",m:"same"},{c:"味",m:"flavor"},{c:"品",m:"goods"},{c:"問",m:"question"},{c:"員",m:"member"},{c:"呼",m:"call"},{c:"告",m:"revelation"},{c:"命",m:"life"},{c:"周",m:"circumference"},{c:"和",m:"harmony"},{c:"唱",m:"chant"},{c:"器",m:"utensil"},{c:"吸",m:"suck"},{c:"吹",m:"blow"}]},
{num:31,rad:"囗",v:[],jp:"くにがまえ",m:"enclosure",k:[{c:"国",m:"country"},{c:"回",m:"times"},{c:"図",m:"map"},{c:"園",m:"park"},{c:"固",m:"harden"},{c:"囲",m:"surround"},{c:"団",m:"group"},{c:"因",m:"cause"},{c:"困",m:"quandary"},{c:"圏",m:"sphere"}]},
{num:32,rad:"土",v:[],jp:"つち",m:"earth",k:[{c:"土",m:"soil"},{c:"地",m:"ground"},{c:"場",m:"place"},{c:"在",m:"exist"},{c:"坂",m:"slope"},{c:"型",m:"mold"},{c:"城",m:"castle"},{c:"基",m:"fundamentals"},{c:"堂",m:"public hall"},{c:"塩",m:"salt"},{c:"境",m:"boundary"},{c:"増",m:"increase"},{c:"壁",m:"wall"},{c:"均",m:"level"},{c:"埋",m:"bury"},{c:"域",m:"range"},{c:"墓",m:"grave"},{c:"塗",m:"paint"},{c:"堅",m:"strict"},{c:"塊",m:"clod"}]},
{num:33,rad:"士",v:[],jp:"さむらい",m:"scholar",k:[{c:"士",m:"gentleman"},{c:"声",m:"voice"},{c:"売",m:"sell"},{c:"壮",m:"robust"},{c:"壱",m:"one (formal)"}]},
{num:34,rad:"夂",v:[],jp:"ふゆがしら",m:"go",k:[{c:"冬",m:"winter"},{c:"各",m:"each"},{c:"条",m:"article"},{c:"夏",m:"summer"}]},
{num:35,rad:"夊",v:[],jp:"すいにょう",m:"go slowly",k:[{c:"夏",m:"summer"},{c:"複",m:"duplicate"}]},
{num:36,rad:"夕",v:[],jp:"ゆうべ",m:"evening",k:[{c:"夕",m:"evening"},{c:"外",m:"outside"},{c:"夜",m:"night"},{c:"多",m:"many"},{c:"夢",m:"dream"},{c:"名",m:"name"}]},
{num:37,rad:"大",v:[],jp:"だい",m:"big",k:[{c:"大",m:"big"},{c:"天",m:"heaven"},{c:"太",m:"plump"},{c:"夫",m:"husband"},{c:"央",m:"center"},{c:"奇",m:"strange"},{c:"奥",m:"interior"},{c:"奨",m:"encourage"},{c:"奏",m:"play music"},{c:"契",m:"pledge"},{c:"奮",m:"stirred up"},{c:"奈",m:"Nara"}]},
{num:38,rad:"女",v:[],jp:"おんな",m:"woman",k:[{c:"女",m:"woman"},{c:"好",m:"fond"},{c:"始",m:"begin"},{c:"姉",m:"elder sister"},{c:"妹",m:"younger sister"},{c:"妻",m:"wife"},{c:"婦",m:"lady"},{c:"姿",m:"figure"},{c:"娘",m:"daughter"},{c:"嫁",m:"marry"},{c:"嫌",m:"dislike"},{c:"妊",m:"pregnancy"},{c:"如",m:"likeness"},{c:"妙",m:"exquisite"},{c:"妨",m:"disturb"},{c:"委",m:"committee"},{c:"威",m:"intimidate"},{c:"婚",m:"marriage"},{c:"嬉",m:"glad"},{c:"姓",m:"surname"}]},
{num:39,rad:"子",v:[],jp:"こ",m:"child",k:[{c:"子",m:"child"},{c:"字",m:"character"},{c:"学",m:"study"},{c:"存",m:"exist"},{c:"季",m:"seasons"},{c:"孝",m:"filial piety"},{c:"孫",m:"grandchild"},{c:"孤",m:"orphan"}]},
{num:40,rad:"宀",v:[],jp:"うかんむり",m:"roof",k:[{c:"家",m:"house"},{c:"安",m:"relax"},{c:"室",m:"room"},{c:"宮",m:"Shinto shrine"},{c:"客",m:"guest"},{c:"実",m:"reality"},{c:"定",m:"determine"},{c:"完",m:"perfect"},{c:"官",m:"bureaucrat"},{c:"守",m:"guard"},{c:"宇",m:"eaves"},{c:"宝",m:"treasure"},{c:"宣",m:"proclaim"},{c:"宿",m:"inn"},{c:"密",m:"secrecy"},{c:"寄",m:"draw near"},{c:"富",m:"wealth"},{c:"察",m:"guess"},{c:"寒",m:"cold"},{c:"寝",m:"lie down"}]},
{num:41,rad:"寸",v:[],jp:"すん",m:"inch",k:[{c:"寸",m:"inch"},{c:"寺",m:"temple"},{c:"対",m:"vis-a-vis"},{c:"封",m:"seal"},{c:"専",m:"specialty"},{c:"射",m:"shoot"},{c:"将",m:"leader"},{c:"導",m:"guidance"},{c:"尊",m:"revered"},{c:"尋",m:"inquire"}]},
{num:42,rad:"小",v:[],jp:"ちいさい",m:"small",k:[{c:"小",m:"little"},{c:"少",m:"few"},{c:"当",m:"hit"},{c:"尚",m:"esteem"}]},
{num:43,rad:"尢",v:["尣"],jp:"まげあし",m:"lame",k:[{c:"尤",m:"especially"},{c:"就",m:"settle"}]},
{num:44,rad:"尸",v:[],jp:"しかばね",m:"corpse",k:[{c:"届",m:"deliver"},{c:"届",m:"deliver"},{c:"屋",m:"roof"},{c:"展",m:"unfold"},{c:"届",m:"deliver"},{c:"局",m:"bureau"},{c:"居",m:"reside"},{c:"属",m:"belong"},{c:"層",m:"stratum"},{c:"尾",m:"tail"},{c:"尿",m:"urine"},{c:"屈",m:"yield"}]},
{num:45,rad:"屮",v:[],jp:"てつ",m:"sprout",k:[{c:"屯",m:"barracks"}]},
{num:46,rad:"山",v:[],jp:"やま",m:"mountain",k:[{c:"山",m:"mountain"},{c:"岸",m:"beach"},{c:"島",m:"island"},{c:"岩",m:"boulder"},{c:"峰",m:"summit"},{c:"崩",m:"crumble"},{c:"嵐",m:"storm"},{c:"崎",m:"promontory"},{c:"岳",m:"peak"},{c:"峠",m:"mountain pass"},{c:"峡",m:"gorge"}]},
{num:47,rad:"巛",v:["川","巜"],jp:"まがりがわ",m:"river",k:[{c:"川",m:"river"},{c:"州",m:"state"},{c:"巡",m:"patrol"},{c:"巣",m:"nest"},{c:"災",m:"disaster"}]},
{num:48,rad:"工",v:[],jp:"たくみ",m:"work",k:[{c:"工",m:"craft"},{c:"左",m:"left"},{c:"差",m:"distinction"},{c:"巧",m:"adroit"},{c:"功",m:"achievement"}]},
{num:49,rad:"己",v:["巳","已"],jp:"おのれ",m:"oneself",k:[{c:"己",m:"self"},{c:"起",m:"wake up"},{c:"記",m:"scribe"},{c:"改",m:"reformation"},{c:"巻",m:"scroll"},{c:"配",m:"distribute"}]},
{num:50,rad:"巾",v:[],jp:"はば",m:"turban",k:[{c:"市",m:"market"},{c:"布",m:"linen"},{c:"帰",m:"homecoming"},{c:"常",m:"usual"},{c:"席",m:"seat"},{c:"帯",m:"sash"},{c:"幕",m:"curtain"},{c:"帳",m:"notebook"},{c:"帽",m:"cap"},{c:"幅",m:"width"},{c:"帆",m:"sail"}]},
{num:51,rad:"干",v:[],jp:"はす",m:"dry",k:[{c:"干",m:"dry"},{c:"平",m:"even"},{c:"年",m:"year"},{c:"幸",m:"happiness"},{c:"幹",m:"tree trunk"}]},
{num:52,rad:"幺",v:[],jp:"いとがしら",m:"short thread",k:[{c:"幼",m:"infancy"},{c:"幻",m:"phantasm"},{c:"幾",m:"how many"}]},
{num:53,rad:"广",v:[],jp:"まだれ",m:"house on cliff",k:[{c:"広",m:"wide"},{c:"店",m:"store"},{c:"度",m:"degrees"},{c:"庭",m:"courtyard"},{c:"庫",m:"warehouse"},{c:"府",m:"borough"},{c:"座",m:"squat"},{c:"床",m:"bed"},{c:"康",m:"sane"},{c:"廊",m:"corridor"},{c:"廃",m:"abolish"},{c:"庁",m:"government office"}]},
{num:54,rad:"廴",v:[],jp:"いんにょう",m:"long stride",k:[{c:"建",m:"build"},{c:"延",m:"prolong"},{c:"廷",m:"courts"}]},
{num:55,rad:"廾",v:[],jp:"にじゅうあし",m:"two hands",k:[{c:"弁",m:"valve"},{c:"弄",m:"play with"},{c:"弊",m:"abuse"}]},
{num:56,rad:"弋",v:[],jp:"しきがまえ",m:"shoot",k:[{c:"式",m:"style"},{c:"弐",m:"two (formal)"}]},
{num:57,rad:"弓",v:[],jp:"ゆみ",m:"bow",k:[{c:"弓",m:"bow"},{c:"引",m:"pull"},{c:"強",m:"strong"},{c:"弱",m:"weak"},{c:"弾",m:"bullet"},{c:"張",m:"lengthen"},{c:"弦",m:"bowstring"},{c:"弧",m:"arc"}]},
{num:58,rad:"彐",v:["彑"],jp:"けいがしら",m:"pig snout",k:[{c:"当",m:"hit"},{c:"帰",m:"homecoming"},{c:"録",m:"record"},{c:"彙",m:"same kind"}]},
{num:59,rad:"彡",v:[],jp:"さんづくり",m:"bristle",k:[{c:"形",m:"shape"},{c:"影",m:"shadow"},{c:"彩",m:"coloring"},{c:"彫",m:"carve"},{c:"彰",m:"patent"}]},
{num:60,rad:"彳",v:[],jp:"ぎょうにんべん",m:"step",k:[{c:"行",m:"going"},{c:"後",m:"behind"},{c:"待",m:"wait"},{c:"得",m:"gain"},{c:"復",m:"restore"},{c:"往",m:"journey"},{c:"径",m:"diameter"},{c:"従",m:"accompany"},{c:"律",m:"rhythm"},{c:"徳",m:"benevolence"},{c:"微",m:"delicate"},{c:"徴",m:"indications"},{c:"徒",m:"junior"},{c:"循",m:"sequential"},{c:"御",m:"honorable"}]},
{num:61,rad:"心",v:["忄"],jp:"こころ",m:"heart",k:[{c:"心",m:"heart"},{c:"思",m:"think"},{c:"意",m:"idea"},{c:"感",m:"emotion"},{c:"想",m:"concept"},{c:"必",m:"invariably"},{c:"急",m:"hurry"},{c:"悪",m:"bad"},{c:"情",m:"feelings"},{c:"性",m:"sex"},{c:"念",m:"wish"},{c:"恋",m:"romance"},{c:"悲",m:"grieve"},{c:"怒",m:"angry"},{c:"忘",m:"forget"},{c:"快",m:"cheerful"},{c:"怖",m:"dreadful"},{c:"悩",m:"trouble"},{c:"慣",m:"accustomed"},{c:"憶",m:"recollection"}]},
{num:62,rad:"戈",v:[],jp:"かのほこ",m:"spear",k:[{c:"成",m:"turn into"},{c:"我",m:"ego"},{c:"戦",m:"war"},{c:"戒",m:"commandment"},{c:"戯",m:"frolic"},{c:"截",m:"cut"},{c:"載",m:"ride"}]},
{num:63,rad:"戸",v:[],jp:"とびらのと",m:"door",k:[{c:"戸",m:"door"},{c:"所",m:"place"},{c:"房",m:"room"},{c:"届",m:"deliver"},{c:"扇",m:"fan"},{c:"扉",m:"front door"}]},
{num:64,rad:"手",v:["扌"],jp:"て",m:"hand",k:[{c:"手",m:"hand"},{c:"打",m:"strike"},{c:"持",m:"hold"},{c:"投",m:"throw"},{c:"指",m:"finger"},{c:"押",m:"push"},{c:"拾",m:"pick up"},{c:"捨",m:"discard"},{c:"探",m:"grope"},{c:"挙",m:"raise"},{c:"振",m:"shake"},{c:"拡",m:"broaden"},{c:"抜",m:"slip out"},{c:"描",m:"sketch"},{c:"掛",m:"hang"},{c:"握",m:"grip"},{c:"招",m:"beckon"},{c:"担",m:"shouldering"},{c:"搬",m:"conveyor"},{c:"操",m:"maneuver"}]},
{num:65,rad:"支",v:[],jp:"しにょう",m:"branch",k:[{c:"支",m:"branch"},{c:"技",m:"skill"},{c:"枝",m:"bough"}]},
{num:66,rad:"攴",v:["攵"],jp:"ぼくづくり",m:"knock",k:[{c:"教",m:"teach"},{c:"数",m:"number"},{c:"整",m:"organize"},{c:"政",m:"politics"},{c:"放",m:"set free"},{c:"敵",m:"enemy"},{c:"救",m:"salvation"},{c:"散",m:"scatter"},{c:"敗",m:"failure"},{c:"故",m:"happenstance"},{c:"敬",m:"awe"},{c:"改",m:"reformation"}]},
{num:67,rad:"文",v:[],jp:"ぶんにょう",m:"script",k:[{c:"文",m:"sentence"},{c:"斉",m:"adjusted"},{c:"斎",m:"purification"}]},
{num:68,rad:"斗",v:[],jp:"とます",m:"dipper",k:[{c:"料",m:"fee"},{c:"斗",m:"Big Dipper"},{c:"斜",m:"diagonal"}]},
{num:69,rad:"斤",v:[],jp:"おの",m:"axe",k:[{c:"新",m:"new"},{c:"近",m:"near"},{c:"所",m:"place"},{c:"断",m:"severance"},{c:"斤",m:"axe"},{c:"斬",m:"kill"}]},
{num:70,rad:"方",v:[],jp:"ほう",m:"square",k:[{c:"方",m:"direction"},{c:"旅",m:"trip"},{c:"族",m:"tribe"},{c:"施",m:"carry out"},{c:"旗",m:"national flag"},{c:"旋",m:"rotation"}]},
{num:71,rad:"无",v:["旡"],jp:"むにょう",m:"have not",k:[{c:"無",m:"nothingness"},{c:"既",m:"previously"}]},
{num:72,rad:"日",v:[],jp:"にち",m:"sun",k:[{c:"日",m:"day"},{c:"時",m:"time"},{c:"早",m:"early"},{c:"明",m:"bright"},{c:"春",m:"spring"},{c:"昼",m:"daytime"},{c:"暗",m:"darkness"},{c:"曜",m:"weekday"},{c:"映",m:"reflect"},{c:"星",m:"star"},{c:"昨",m:"yesterday"},{c:"暑",m:"sultry"},{c:"暖",m:"warmth"},{c:"昔",m:"once upon"},{c:"景",m:"scenery"},{c:"晩",m:"nightfall"},{c:"曇",m:"cloudy"},{c:"暮",m:"livelihood"},{c:"暴",m:"outburst"},{c:"晴",m:"clear up"}]},
{num:73,rad:"曰",v:[],jp:"いわく",m:"say",k:[{c:"曲",m:"bend"},{c:"書",m:"write"},{c:"最",m:"utmost"},{c:"替",m:"exchange"}]},
{num:74,rad:"月",v:[],jp:"つき",m:"moon",k:[{c:"月",m:"month"},{c:"有",m:"possess"},{c:"期",m:"period"},{c:"朝",m:"morning"},{c:"朗",m:"melodious"},{c:"望",m:"ambition"},{c:"服",m:"clothing"},{c:"肉",m:"meat"},{c:"胸",m:"bosom"},{c:"脳",m:"brain"},{c:"腕",m:"arm"},{c:"腹",m:"abdomen"},{c:"背",m:"stature"},{c:"肌",m:"texture"},{c:"脂",m:"fat"},{c:"膝",m:"knee"},{c:"臓",m:"entrails"},{c:"腰",m:"loins"},{c:"股",m:"thigh"},{c:"肺",m:"lungs"}]},
{num:75,rad:"木",v:[],jp:"き",m:"tree",k:[{c:"木",m:"tree"},{c:"本",m:"book"},{c:"校",m:"school"},{c:"林",m:"grove"},{c:"森",m:"forest"},{c:"村",m:"village"},{c:"東",m:"east"},{c:"松",m:"pine"},{c:"板",m:"board"},{c:"橋",m:"bridge"},{c:"様",m:"Esq."},{c:"横",m:"sideways"},{c:"根",m:"root"},{c:"植",m:"plant"},{c:"柱",m:"pillar"},{c:"桜",m:"cherry"},{c:"棒",m:"rod"},{c:"札",m:"tag"},{c:"机",m:"desk"},{c:"杯",m:"counter for cupfuls"}]},
{num:76,rad:"欠",v:[],jp:"あくび",m:"yawn",k:[{c:"次",m:"next"},{c:"歌",m:"song"},{c:"欲",m:"longing"},{c:"歓",m:"delight"},{c:"欧",m:"Europe"},{c:"款",m:"goodwill"},{c:"欺",m:"deceive"}]},
{num:77,rad:"止",v:[],jp:"とめる",m:"stop",k:[{c:"止",m:"stop"},{c:"正",m:"correct"},{c:"歩",m:"walk"},{c:"歴",m:"curriculum"},{c:"歳",m:"year-end"},{c:"武",m:"warrior"},{c:"此",m:"this"}]},
{num:78,rad:"歹",v:["歺"],jp:"がつへん",m:"death",k:[{c:"死",m:"death"},{c:"残",m:"remainder"},{c:"殊",m:"particularly"},{c:"殖",m:"augment"},{c:"殿",m:"Mr."}]},
{num:79,rad:"殳",v:[],jp:"ほこつくり",m:"weapon",k:[{c:"段",m:"grade"},{c:"殺",m:"kill"},{c:"殻",m:"husk"},{c:"般",m:"carrier"},{c:"設",m:"establishment"},{c:"投",m:"throw"},{c:"役",m:"duty"}]},
{num:80,rad:"毋",v:["母"],jp:"なかれ",m:"do not",k:[{c:"母",m:"mother"},{c:"毎",m:"every"},{c:"毒",m:"poison"}]},
{num:81,rad:"比",v:[],jp:"くらべる",m:"compare",k:[{c:"比",m:"compare"},{c:"皆",m:"all"},{c:"批",m:"criticism"}]},
{num:82,rad:"毛",v:[],jp:"け",m:"fur",k:[{c:"毛",m:"fur"},{c:"毫",m:"fine hair"}]},
{num:83,rad:"氏",v:[],jp:"うじ",m:"clan",k:[{c:"氏",m:"family name"},{c:"民",m:"people"},{c:"紙",m:"paper"}]},
{num:84,rad:"气",v:[],jp:"きがまえ",m:"steam",k:[{c:"気",m:"spirit"},{c:"酸",m:"acid"}]},
{num:85,rad:"水",v:["氵","氺"],jp:"みず",m:"water",k:[{c:"水",m:"water"},{c:"海",m:"sea"},{c:"池",m:"pond"},{c:"河",m:"river"},{c:"洗",m:"wash"},{c:"流",m:"current"},{c:"決",m:"decide"},{c:"法",m:"method"},{c:"消",m:"extinguish"},{c:"活",m:"lively"},{c:"深",m:"deep"},{c:"注",m:"pour"},{c:"湖",m:"lake"},{c:"港",m:"harbor"},{c:"温",m:"warm"},{c:"泳",m:"swim"},{c:"波",m:"waves"},{c:"油",m:"oil"},{c:"清",m:"pure"},{c:"満",m:"full"}]},
{num:86,rad:"火",v:["灬"],jp:"ひ",m:"fire",k:[{c:"火",m:"fire"},{c:"炎",m:"inflammation"},{c:"然",m:"sort of thing"},{c:"焼",m:"bake"},{c:"煙",m:"smoke"},{c:"照",m:"illuminate"},{c:"熱",m:"heat"},{c:"燃",m:"burn"},{c:"灯",m:"lamp"},{c:"烈",m:"ardent"},{c:"煮",m:"boil"},{c:"蒸",m:"steam"},{c:"点",m:"spot"},{c:"熊",m:"bear"},{c:"炭",m:"charcoal"}]},
{num:87,rad:"爪",v:["爫"],jp:"つめ",m:"claw",k:[{c:"爪",m:"claw"},{c:"采",m:"pick"},{c:"爵",m:"baron"}]},
{num:88,rad:"父",v:[],jp:"ちち",m:"father",k:[{c:"父",m:"father"},{c:"爺",m:"old man"}]},
{num:89,rad:"爻",v:[],jp:"まじわる",m:"mix",k:[{c:"爽",m:"refreshing"}]},
{num:90,rad:"爿",v:["丬"],jp:"しょうへん",m:"split wood",k:[{c:"壮",m:"robust"},{c:"状",m:"status"},{c:"将",m:"leader"}]},
{num:91,rad:"片",v:[],jp:"かた",m:"slice",k:[{c:"片",m:"one-sided"},{c:"版",m:"printing block"},{c:"牌",m:"signboard"}]},
{num:92,rad:"牙",v:[],jp:"きばへん",m:"fang",k:[{c:"牙",m:"fang"},{c:"雅",m:"gracious"}]},
{num:93,rad:"牛",v:["牜"],jp:"うし",m:"cow",k:[{c:"牛",m:"cow"},{c:"物",m:"thing"},{c:"特",m:"special"},{c:"牧",m:"breed"},{c:"牲",m:"animal sacrifice"},{c:"犠",m:"sacrifice"}]},
{num:94,rad:"犬",v:["犭"],jp:"いぬ",m:"dog",k:[{c:"犬",m:"dog"},{c:"犯",m:"crime"},{c:"状",m:"conditions"},{c:"独",m:"single"},{c:"狭",m:"cramped"},{c:"猫",m:"cat"},{c:"狂",m:"lunatic"},{c:"獲",m:"seize"},{c:"猛",m:"fierce"},{c:"献",m:"offering"},{c:"猟",m:"hunting"},{c:"猿",m:"monkey"}]},
{num:95,rad:"玄",v:[],jp:"げん",m:"dark",k:[{c:"玄",m:"mysterious"},{c:"率",m:"ratio"}]},
{num:96,rad:"玉",v:["王"],jp:"たま",m:"jade",k:[{c:"玉",m:"jewel"},{c:"王",m:"king"},{c:"理",m:"logic"},{c:"現",m:"present"},{c:"球",m:"ball"},{c:"環",m:"ring"},{c:"班",m:"squad"},{c:"珍",m:"rare"},{c:"琴",m:"harp"},{c:"瑠",m:"lapis lazuli"}]},
{num:97,rad:"瓜",v:[],jp:"うり",m:"melon",k:[{c:"瓜",m:"melon"}]},
{num:98,rad:"瓦",v:[],jp:"かわら",m:"tile",k:[{c:"瓦",m:"tile"},{c:"瓶",m:"bottle"}]},
{num:99,rad:"甘",v:[],jp:"あまい",m:"sweet",k:[{c:"甘",m:"sweet"},{c:"甚",m:"tremendously"}]},
{num:100,rad:"生",v:[],jp:"うまれる",m:"life",k:[{c:"生",m:"life"},{c:"産",m:"products"},{c:"姓",m:"surname"}]},
{num:101,rad:"用",v:[],jp:"もちいる",m:"use",k:[{c:"用",m:"utilize"},{c:"備",m:"equip"}]},
{num:102,rad:"田",v:[],jp:"た",m:"field",k:[{c:"田",m:"rice field"},{c:"男",m:"male"},{c:"町",m:"town"},{c:"界",m:"world"},{c:"番",m:"turn"},{c:"畑",m:"farm"},{c:"画",m:"brush-stroke"},{c:"略",m:"abbreviation"},{c:"留",m:"detain"},{c:"異",m:"uncommon"},{c:"畜",m:"livestock"},{c:"畳",m:"tatami"}]},
{num:103,rad:"疋",v:[],jp:"ひき",m:"bolt of cloth",k:[{c:"疋",m:"bolt of cloth"},{c:"疑",m:"doubt"}]},
{num:104,rad:"疒",v:[],jp:"やまいだれ",m:"sickness",k:[{c:"病",m:"ill"},{c:"痛",m:"pain"},{c:"疲",m:"exhausted"},{c:"症",m:"symptoms"},{c:"療",m:"heal"},{c:"癒",m:"healing"},{c:"痩",m:"get thin"},{c:"疫",m:"epidemic"},{c:"痕",m:"mark"}]},
{num:105,rad:"癶",v:[],jp:"はつがしら",m:"footsteps",k:[{c:"発",m:"departure"},{c:"登",m:"ascend"}]},
{num:106,rad:"白",v:[],jp:"しろ",m:"white",k:[{c:"白",m:"white"},{c:"百",m:"hundred"},{c:"的",m:"bull's eye"},{c:"皇",m:"emperor"},{c:"皆",m:"all"},{c:"泉",m:"spring"}]},
{num:107,rad:"皮",v:[],jp:"けがわ",m:"skin",k:[{c:"皮",m:"skin"},{c:"彼",m:"he"},{c:"被",m:"incur"},{c:"破",m:"rend"},{c:"波",m:"waves"}]},
{num:108,rad:"皿",v:[],jp:"さら",m:"dish",k:[{c:"皿",m:"dish"},{c:"盛",m:"boom"},{c:"盗",m:"steal"},{c:"監",m:"oversee"},{c:"益",m:"benefit"},{c:"盟",m:"alliance"}]},
{num:109,rad:"目",v:[],jp:"め",m:"eye",k:[{c:"目",m:"eye"},{c:"見",m:"see"},{c:"直",m:"straightaway"},{c:"真",m:"true"},{c:"相",m:"inter-"},{c:"着",m:"don"},{c:"省",m:"focus"},{c:"眠",m:"sleep"},{c:"眼",m:"eyeball"},{c:"瞬",m:"wink"},{c:"睡",m:"drowsy"},{c:"督",m:"coach"},{c:"瞳",m:"pupil"}]},
{num:110,rad:"矛",v:[],jp:"むのほこ",m:"spear",k:[{c:"矛",m:"halberd"},{c:"矛盾",m:"contradiction"}]},
{num:111,rad:"矢",v:[],jp:"や",m:"arrow",k:[{c:"矢",m:"arrow"},{c:"知",m:"know"},{c:"短",m:"short"},{c:"矩",m:"carpenter's square"}]},
{num:112,rad:"石",v:[],jp:"いし",m:"stone",k:[{c:"石",m:"stone"},{c:"研",m:"polish"},{c:"確",m:"assurance"},{c:"破",m:"rend"},{c:"磁",m:"magnet"},{c:"礎",m:"cornerstone"},{c:"碑",m:"tombstone"},{c:"砂",m:"sand"},{c:"砲",m:"cannon"},{c:"硬",m:"stiff"}]},
{num:113,rad:"示",v:["礻"],jp:"しめす",m:"sign",k:[{c:"社",m:"company"},{c:"神",m:"gods"},{c:"祭",m:"ritual"},{c:"福",m:"blessing"},{c:"禁",m:"prohibition"},{c:"祈",m:"pray"},{c:"礼",m:"salute"},{c:"祝",m:"celebrate"},{c:"票",m:"ballot"},{c:"禅",m:"zen"}]},
{num:114,rad:"禸",v:[],jp:"ぐうのあし",m:"track",k:[{c:"禹",m:"Yu the Great"}]},
{num:115,rad:"禾",v:[],jp:"のぎ",m:"grain",k:[{c:"私",m:"private"},{c:"秋",m:"autumn"},{c:"科",m:"department"},{c:"種",m:"species"},{c:"積",m:"volume"},{c:"程",m:"extent"},{c:"税",m:"tax"},{c:"称",m:"call"},{c:"移",m:"shift"},{c:"稲",m:"rice plant"},{c:"穫",m:"reap"},{c:"穂",m:"ear of grain"},{c:"秘",m:"secret"},{c:"稼",m:"earnings"}]},
{num:116,rad:"穴",v:[],jp:"あな",m:"cave",k:[{c:"穴",m:"hole"},{c:"空",m:"empty"},{c:"究",m:"research"},{c:"窓",m:"window"},{c:"窮",m:"hard pressed"},{c:"窃",m:"stealth"},{c:"窒",m:"plug up"}]},
{num:117,rad:"立",v:[],jp:"たつ",m:"stand",k:[{c:"立",m:"stand up"},{c:"音",m:"sound"},{c:"親",m:"parent"},{c:"章",m:"badge"},{c:"競",m:"emulate"},{c:"端",m:"edge"},{c:"童",m:"juvenile"},{c:"産",m:"products"}]},
{num:118,rad:"竹",v:[],jp:"たけ",m:"bamboo",k:[{c:"竹",m:"bamboo"},{c:"第",m:"No."},{c:"笑",m:"laugh"},{c:"算",m:"calculate"},{c:"等",m:"etc."},{c:"答",m:"solution"},{c:"管",m:"pipe"},{c:"箱",m:"box"},{c:"節",m:"node"},{c:"筆",m:"writing brush"},{c:"簡",m:"simplicity"},{c:"範",m:"pattern"},{c:"策",m:"scheme"},{c:"籍",m:"register"},{c:"篇",m:"volume"}]},
{num:119,rad:"米",v:[],jp:"こめ",m:"rice",k:[{c:"米",m:"rice"},{c:"精",m:"refined"},{c:"粉",m:"flour"},{c:"糖",m:"sugar"},{c:"糧",m:"provisions"},{c:"粒",m:"grains"},{c:"粗",m:"coarse"},{c:"粘",m:"sticky"}]},
{num:120,rad:"糸",v:["糹"],jp:"いと",m:"silk",k:[{c:"糸",m:"thread"},{c:"紙",m:"paper"},{c:"組",m:"association"},{c:"線",m:"line"},{c:"練",m:"practice"},{c:"結",m:"tie"},{c:"経",m:"sutra"},{c:"終",m:"end"},{c:"絵",m:"picture"},{c:"続",m:"continue"},{c:"縁",m:"affinity"},{c:"約",m:"promise"},{c:"細",m:"dainty"},{c:"絡",m:"entwine"},{c:"織",m:"weave"},{c:"縮",m:"shrink"},{c:"純",m:"genuine"},{c:"緊",m:"tense"},{c:"維",m:"fiber"},{c:"締",m:"tighten"}]},
{num:121,rad:"缶",v:[],jp:"ほとぎ",m:"jar",k:[{c:"缶",m:"tin can"},{c:"缺",m:"lack"}]},
{num:122,rad:"网",v:["罒","罓"],jp:"あみがしら",m:"net",k:[{c:"置",m:"put"},{c:"罪",m:"guilt"},{c:"罰",m:"penalty"},{c:"署",m:"government office"},{c:"買",m:"buy"},{c:"罵",m:"abuse"}]},
{num:123,rad:"羊",v:[],jp:"ひつじ",m:"sheep",k:[{c:"羊",m:"sheep"},{c:"美",m:"beauty"},{c:"義",m:"righteousness"},{c:"善",m:"virtuous"},{c:"着",m:"don"},{c:"群",m:"flock"},{c:"養",m:"foster"},{c:"鮮",m:"fresh"}]},
{num:124,rad:"羽",v:[],jp:"はね",m:"feather",k:[{c:"羽",m:"feathers"},{c:"習",m:"learn"},{c:"翌",m:"the following"},{c:"翼",m:"wing"},{c:"翔",m:"soar"},{c:"翻",m:"flip"}]},
{num:125,rad:"老",v:["耂"],jp:"おい",m:"old",k:[{c:"老",m:"old man"},{c:"者",m:"someone"},{c:"考",m:"consider"}]},
{num:126,rad:"而",v:[],jp:"しかして",m:"beard",k:[{c:"而",m:"and yet"},{c:"耐",m:"endure"}]},
{num:127,rad:"耒",v:[],jp:"らいすき",m:"plow",k:[{c:"耕",m:"plow"},{c:"耗",m:"decrease"}]},
{num:128,rad:"耳",v:[],jp:"みみ",m:"ear",k:[{c:"耳",m:"ear"},{c:"聞",m:"hear"},{c:"職",m:"post"},{c:"聖",m:"holy"},{c:"聴",m:"listen"},{c:"聡",m:"wise"}]},
{num:129,rad:"聿",v:[],jp:"ふでづくり",m:"brush",k:[{c:"書",m:"write"},{c:"筆",m:"writing brush"},{c:"建",m:"build"},{c:"律",m:"rhythm"}]},
{num:130,rad:"肉",v:[],jp:"にく",m:"meat",k:[{c:"肉",m:"meat"},{c:"肥",m:"fertilizer"},{c:"育",m:"bring up"},{c:"能",m:"ability"},{c:"脅",m:"threaten"}]},
{num:131,rad:"臣",v:[],jp:"しん",m:"minister",k:[{c:"臣",m:"retainer"},{c:"臨",m:"look to"},{c:"蔵",m:"storehouse"}]},
{num:132,rad:"自",v:[],jp:"みずから",m:"self",k:[{c:"自",m:"oneself"},{c:"臭",m:"stinking"},{c:"息",m:"breath"}]},
{num:133,rad:"至",v:[],jp:"いたる",m:"arrive",k:[{c:"至",m:"climax"},{c:"致",m:"do"},{c:"台",m:"pedestal"}]},
{num:134,rad:"臼",v:[],jp:"うす",m:"mortar",k:[{c:"臼",m:"mortar"},{c:"興",m:"entertain"},{c:"挙",m:"raise"}]},
{num:135,rad:"舌",v:[],jp:"した",m:"tongue",k:[{c:"舌",m:"tongue"},{c:"話",m:"tale"},{c:"活",m:"lively"},{c:"乱",m:"riot"}]},
{num:136,rad:"舛",v:[],jp:"ます",m:"opposite",k:[{c:"舞",m:"dance"},{c:"舜",m:"type of morning glory"}]},
{num:137,rad:"舟",v:[],jp:"ふね",m:"boat",k:[{c:"舟",m:"boat"},{c:"船",m:"ship"},{c:"航",m:"navigate"},{c:"般",m:"carrier"},{c:"艦",m:"warship"},{c:"艇",m:"rowboat"}]},
{num:138,rad:"艮",v:[],jp:"うしとら",m:"stopping",k:[{c:"良",m:"good"},{c:"食",m:"eat"},{c:"根",m:"root"},{c:"銀",m:"silver"},{c:"退",m:"retreat"},{c:"限",m:"limit"},{c:"既",m:"previously"},{c:"即",m:"instant"}]},
{num:139,rad:"色",v:[],jp:"いろ",m:"colour",k:[{c:"色",m:"color"},{c:"絶",m:"discontinue"}]},
{num:140,rad:"艸",v:["艹"],jp:"くさ",m:"grass",k:[{c:"花",m:"flower"},{c:"草",m:"grass"},{c:"茶",m:"tea"},{c:"薬",m:"medicine"},{c:"英",m:"England"},{c:"落",m:"fall"},{c:"葉",m:"leaf"},{c:"若",m:"young"},{c:"苦",m:"suffering"},{c:"荷",m:"baggage"},{c:"菜",m:"vegetable"},{c:"蒸",m:"steam"},{c:"芸",m:"technique"},{c:"藤",m:"wisteria"},{c:"華",m:"splendor"},{c:"著",m:"renowned"},{c:"薄",m:"dilute"},{c:"蔵",m:"storehouse"},{c:"蓄",m:"amass"},{c:"範",m:"pattern"}]},
{num:141,rad:"虍",v:[],jp:"とらかんむり",m:"tiger stripes",k:[{c:"虎",m:"tiger"},{c:"虐",m:"tyrannize"},{c:"虚",m:"void"},{c:"慮",m:"prudence"}]},
{num:142,rad:"虫",v:[],jp:"むし",m:"insect",k:[{c:"虫",m:"insect"},{c:"蛇",m:"snake"},{c:"蝶",m:"butterfly"},{c:"蚊",m:"mosquito"},{c:"蜂",m:"bee"},{c:"蛙",m:"frog"},{c:"融",m:"dissolve"},{c:"蛍",m:"firefly"},{c:"蜜",m:"honey"},{c:"蟻",m:"ant"}]},
{num:143,rad:"血",v:[],jp:"ち",m:"blood",k:[{c:"血",m:"blood"},{c:"衆",m:"masses"}]},
{num:144,rad:"行",v:[],jp:"ぎょう",m:"go",k:[{c:"行",m:"going"},{c:"術",m:"art"},{c:"街",m:"boulevard"},{c:"衛",m:"defense"},{c:"衝",m:"collide"},{c:"衡",m:"equilibrium"}]},
{num:145,rad:"衣",v:["衤"],jp:"ころも",m:"clothes",k:[{c:"衣",m:"garment"},{c:"表",m:"surface"},{c:"裏",m:"back"},{c:"被",m:"incur"},{c:"袋",m:"sack"},{c:"複",m:"duplicate"},{c:"製",m:"made in"},{c:"装",m:"attire"},{c:"補",m:"supplement"},{c:"裕",m:"abundant"},{c:"裸",m:"naked"},{c:"襟",m:"collar"},{c:"裂",m:"split"}]},
{num:146,rad:"西",v:["襾","覀"],jp:"にし",m:"west",k:[{c:"西",m:"west"},{c:"要",m:"need"},{c:"覆",m:"capsize"},{c:"覇",m:"hegemony"}]},
{num:147,rad:"見",v:[],jp:"みる",m:"see",k:[{c:"見",m:"see"},{c:"親",m:"parent"},{c:"観",m:"outlook"},{c:"覚",m:"memorize"},{c:"規",m:"standard"},{c:"視",m:"inspection"},{c:"覧",m:"perusal"}]},
{num:148,rad:"角",v:[],jp:"つの",m:"horn",k:[{c:"角",m:"angle"},{c:"解",m:"unravel"},{c:"触",m:"contact"},{c:"解",m:"unravel"}]},
{num:149,rad:"言",v:["訁"],jp:"ことば",m:"speech",k:[{c:"言",m:"say"},{c:"語",m:"word"},{c:"話",m:"tale"},{c:"計",m:"plot"},{c:"記",m:"scribe"},{c:"読",m:"read"},{c:"説",m:"opinion"},{c:"調",m:"tune"},{c:"議",m:"deliberation"},{c:"証",m:"evidence"},{c:"試",m:"test"},{c:"訪",m:"call on"},{c:"許",m:"permit"},{c:"評",m:"evaluate"},{c:"認",m:"acknowledge"},{c:"論",m:"argument"},{c:"誤",m:"mistake"},{c:"詳",m:"detailed"},{c:"課",m:"chapter"},{c:"謝",m:"apologize"}]},
{num:150,rad:"谷",v:[],jp:"たに",m:"valley",k:[{c:"谷",m:"valley"},{c:"欲",m:"longing"},{c:"容",m:"contain"},{c:"浴",m:"bathe"}]},
{num:151,rad:"豆",v:[],jp:"まめ",m:"bean",k:[{c:"豆",m:"beans"},{c:"頭",m:"head"},{c:"短",m:"short"},{c:"豊",m:"bountiful"},{c:"登",m:"ascend"}]},
{num:152,rad:"豕",v:[],jp:"いのこ",m:"pig",k:[{c:"豚",m:"pork"},{c:"象",m:"elephant"},{c:"家",m:"house"},{c:"豪",m:"overpowering"}]},
{num:153,rad:"豸",v:[],jp:"むじな",m:"badger",k:[{c:"貌",m:"countenance"},{c:"貊",m:"northern barbarians"}]},
{num:154,rad:"貝",v:[],jp:"かい",m:"shell",k:[{c:"貝",m:"shellfish"},{c:"買",m:"buy"},{c:"売",m:"sell"},{c:"質",m:"substance"},{c:"負",m:"defeat"},{c:"貸",m:"lend"},{c:"資",m:"capital"},{c:"費",m:"expense"},{c:"賛",m:"approve"},{c:"賃",m:"fare"},{c:"財",m:"property"},{c:"貯",m:"savings"},{c:"賢",m:"intelligent"},{c:"貧",m:"poverty"},{c:"貴",m:"precious"},{c:"賞",m:"prize"},{c:"購",m:"subscription"},{c:"贈",m:"presents"},{c:"賄",m:"bribe"},{c:"貢",m:"tribute"}]},
{num:155,rad:"赤",v:[],jp:"あか",m:"red",k:[{c:"赤",m:"red"},{c:"赦",m:"pardon"},{c:"赫",m:"suddenly"}]},
{num:156,rad:"走",v:[],jp:"はしる",m:"run",k:[{c:"走",m:"run"},{c:"起",m:"wake up"},{c:"超",m:"transcend"},{c:"越",m:"surpass"},{c:"趣",m:"gist"},{c:"赴",m:"proceed"}]},
{num:157,rad:"足",v:[],jp:"あし",m:"foot",k:[{c:"足",m:"leg"},{c:"路",m:"path"},{c:"踊",m:"jump"},{c:"距",m:"long-distance"},{c:"跡",m:"tracks"},{c:"踏",m:"step"},{c:"蹴",m:"kick"},{c:"跳",m:"hop"},{c:"践",m:"tread"},{c:"躍",m:"leap"}]},
{num:158,rad:"身",v:[],jp:"み",m:"body",k:[{c:"身",m:"somebody"},{c:"射",m:"shoot"},{c:"躯",m:"body"}]},
{num:159,rad:"車",v:[],jp:"くるま",m:"cart",k:[{c:"車",m:"car"},{c:"転",m:"revolve"},{c:"軽",m:"lightly"},{c:"輪",m:"wheel"},{c:"運",m:"carry"},{c:"連",m:"take along"},{c:"載",m:"ride"},{c:"軍",m:"army"},{c:"輸",m:"transport"},{c:"較",m:"contrast"},{c:"輝",m:"radiance"},{c:"軸",m:"axis"},{c:"轄",m:"control"}]},
{num:160,rad:"辛",v:[],jp:"からい",m:"bitter",k:[{c:"辛",m:"spicy"},{c:"辞",m:"resign"},{c:"辟",m:"false"}]},
{num:161,rad:"辰",v:[],jp:"しんのたつ",m:"morning",k:[{c:"辰",m:"sign of the dragon"},{c:"農",m:"agriculture"},{c:"振",m:"shake"}]},
{num:162,rad:"辵",v:["辶"],jp:"しんにゅう",m:"walk",k:[{c:"近",m:"near"},{c:"通",m:"traffic"},{c:"道",m:"road"},{c:"進",m:"advance"},{c:"送",m:"send"},{c:"週",m:"week"},{c:"達",m:"accomplished"},{c:"遊",m:"play"},{c:"速",m:"quick"},{c:"運",m:"carry"},{c:"返",m:"return"},{c:"選",m:"elect"},{c:"遠",m:"distant"},{c:"退",m:"retreat"},{c:"逃",m:"escape"},{c:"追",m:"chase"},{c:"連",m:"take along"},{c:"過",m:"overdo"},{c:"適",m:"suitable"},{c:"迷",m:"astray"}]},
{num:163,rad:"邑",v:["阝"],jp:"おおざと",m:"town",k:[{c:"部",m:"section"},{c:"都",m:"metropolis"},{c:"郡",m:"county"},{c:"郎",m:"son"},{c:"郊",m:"outskirts"},{c:"邦",m:"home country"},{c:"郵",m:"mail"},{c:"邪",m:"wicked"},{c:"那",m:"what"}]},
{num:164,rad:"酉",v:[],jp:"とりへん",m:"wine",k:[{c:"酒",m:"sake"},{c:"配",m:"distribute"},{c:"酸",m:"acid"},{c:"酔",m:"drunk"},{c:"醸",m:"brew"},{c:"酢",m:"vinegar"},{c:"醜",m:"ugly"},{c:"酷",m:"cruel"},{c:"醒",m:"awakening"}]},
{num:165,rad:"釆",v:[],jp:"のごめ",m:"distinguish",k:[{c:"釈",m:"explanation"},{c:"番",m:"turn"}]},
{num:166,rad:"里",v:[],jp:"さと",m:"village",k:[{c:"里",m:"ri (measure)"},{c:"野",m:"plains"},{c:"理",m:"logic"},{c:"量",m:"quantity"},{c:"重",m:"heavy"},{c:"黒",m:"black"}]},
{num:167,rad:"金",v:["釒"],jp:"かね",m:"metal",k:[{c:"金",m:"gold"},{c:"銀",m:"silver"},{c:"鉄",m:"iron"},{c:"針",m:"needle"},{c:"鋭",m:"pointed"},{c:"鏡",m:"mirror"},{c:"鐘",m:"bell"},{c:"銅",m:"copper"},{c:"錦",m:"brocade"},{c:"鋼",m:"steel"},{c:"録",m:"record"},{c:"鍵",m:"key"},{c:"鎖",m:"chain"},{c:"銃",m:"gun"},{c:"錯",m:"confused"},{c:"鍛",m:"forge"},{c:"錠",m:"lock"}]},
{num:168,rad:"長",v:[],jp:"ながい",m:"long",k:[{c:"長",m:"long"},{c:"髪",m:"hair of the head"}]},
{num:169,rad:"門",v:[],jp:"もん",m:"gate",k:[{c:"門",m:"gate"},{c:"間",m:"interval"},{c:"開",m:"open"},{c:"関",m:"connection"},{c:"閉",m:"closed"},{c:"聞",m:"hear"},{c:"闘",m:"fight"},{c:"閣",m:"tower"},{c:"閲",m:"review"},{c:"闇",m:"darkness"}]},
{num:170,rad:"阜",v:["阝"],jp:"ぎふのふ",m:"mound",k:[{c:"院",m:"Inst."},{c:"陽",m:"sunshine"},{c:"降",m:"descend"},{c:"防",m:"ward off"},{c:"限",m:"limit"},{c:"際",m:"occasion"},{c:"階",m:"storey"},{c:"陸",m:"land"},{c:"隣",m:"neighboring"},{c:"険",m:"precipitous"},{c:"隠",m:"conceal"},{c:"障",m:"hinder"},{c:"陰",m:"shade"},{c:"隊",m:"regiment"},{c:"随",m:"follow"}]},
{num:171,rad:"隶",v:[],jp:"れいづくり",m:"slave",k:[{c:"隷",m:"slave"}]},
{num:172,rad:"隹",v:[],jp:"ふるとり",m:"small bird",k:[{c:"集",m:"gather"},{c:"雑",m:"miscellaneous"},{c:"難",m:"difficult"},{c:"雄",m:"masculine"},{c:"雅",m:"gracious"},{c:"雌",m:"feminine"},{c:"雇",m:"employ"},{c:"離",m:"detach"},{c:"隻",m:"vessels"}]},
{num:173,rad:"雨",v:[],jp:"あめ",m:"rain",k:[{c:"雨",m:"rain"},{c:"雲",m:"cloud"},{c:"雪",m:"snow"},{c:"雷",m:"thunder"},{c:"電",m:"electricity"},{c:"霧",m:"fog"},{c:"露",m:"dew"},{c:"震",m:"quake"},{c:"霜",m:"frost"},{c:"霊",m:"spirits"}]},
{num:174,rad:"青",v:["靑"],jp:"あお",m:"blue",k:[{c:"青",m:"blue"},{c:"静",m:"quiet"},{c:"清",m:"pure"},{c:"情",m:"feelings"},{c:"精",m:"refined"},{c:"晴",m:"clear up"}]},
{num:175,rad:"非",v:[],jp:"あらず",m:"wrong",k:[{c:"非",m:"un-"},{c:"悲",m:"grieve"},{c:"罪",m:"guilt"},{c:"排",m:"repudiate"},{c:"俳",m:"haiku"}]},
{num:176,rad:"面",v:[],jp:"めん",m:"face",k:[{c:"面",m:"mask"},{c:"麺",m:"noodles"}]},
{num:177,rad:"革",v:[],jp:"かくのかわ",m:"leather",k:[{c:"革",m:"leather"},{c:"靴",m:"shoes"},{c:"鞄",m:"suitcase"}]},
{num:178,rad:"韋",v:[],jp:"なめしがわ",m:"tanned leather",k:[{c:"韓",m:"Korea"},{c:"違",m:"differ"},{c:"偉",m:"admirable"},{c:"緯",m:"horizontal"}]},
{num:179,rad:"韭",v:[],jp:"にら",m:"leek",k:[{c:"韭",m:"leek"}]},
{num:180,rad:"音",v:[],jp:"おと",m:"sound",k:[{c:"音",m:"sound"},{c:"意",m:"idea"},{c:"暗",m:"darkness"},{c:"韻",m:"rhyme"}]},
{num:181,rad:"頁",v:[],jp:"おおがい",m:"leaf",k:[{c:"頭",m:"head"},{c:"顔",m:"face"},{c:"題",m:"topic"},{c:"類",m:"sort"},{c:"額",m:"forehead"},{c:"願",m:"petition"},{c:"順",m:"obey"},{c:"頂",m:"place on the head"},{c:"領",m:"jurisdiction"},{c:"頼",m:"trust"},{c:"預",m:"deposit"},{c:"頑",m:"stubborn"},{c:"項",m:"paragraph"},{c:"顧",m:"look back"},{c:"頻",m:"repeatedly"}]},
{num:182,rad:"風",v:[],jp:"かぜ",m:"wind",k:[{c:"風",m:"wind"},{c:"颯",m:"sudden"},{c:"飄",m:"drift"}]},
{num:183,rad:"飛",v:[],jp:"とぶ",m:"fly",k:[{c:"飛",m:"fly"}]},
{num:184,rad:"食",v:["飠"],jp:"しょく",m:"eat",k:[{c:"食",m:"eat"},{c:"飲",m:"drink"},{c:"館",m:"building"},{c:"飯",m:"meal"},{c:"飾",m:"decorate"},{c:"飼",m:"domesticate"},{c:"飢",m:"hungry"},{c:"餓",m:"starve"},{c:"養",m:"foster"},{c:"餅",m:"mochi"}]},
{num:185,rad:"首",v:[],jp:"くび",m:"head",k:[{c:"首",m:"neck"},{c:"道",m:"road"}]},
{num:186,rad:"香",v:[],jp:"においこう",m:"fragrant",k:[{c:"香",m:"incense"},{c:"馨",m:"fragrant"}]},
{num:187,rad:"馬",v:[],jp:"うま",m:"horse",k:[{c:"馬",m:"horse"},{c:"駅",m:"station"},{c:"駐",m:"parking"},{c:"験",m:"verification"},{c:"騒",m:"boisterous"},{c:"駆",m:"drive"},{c:"騎",m:"equestrian"},{c:"駄",m:"burdensome"}]},
{num:188,rad:"骨",v:[],jp:"ほね",m:"bone",k:[{c:"骨",m:"skeleton"},{c:"髄",m:"marrow"},{c:"滑",m:"slippery"},{c:"骸",m:"body"}]},
{num:189,rad:"高",v:["髙"],jp:"たかい",m:"tall",k:[{c:"高",m:"tall"}]},
{num:190,rad:"髟",v:[],jp:"かみがしら",m:"hair",k:[{c:"髪",m:"hair"},{c:"髭",m:"beard"},{c:"鬢",m:"sideburns"}]},
{num:191,rad:"鬥",v:[],jp:"とうがまえ",m:"fight",k:[{c:"闘",m:"fight"},{c:"闘",m:"fight"}]},
{num:192,rad:"鬯",v:[],jp:"ちょう",m:"sacrificial wine",k:[{c:"鬱",m:"gloom"}]},
{num:193,rad:"鬲",v:[],jp:"かなえ",m:"tripod",k:[{c:"融",m:"dissolve"}]},
{num:194,rad:"鬼",v:[],jp:"おに",m:"ghost",k:[{c:"鬼",m:"ghost"},{c:"魂",m:"soul"},{c:"魔",m:"demon"},{c:"魅",m:"fascination"}]},
{num:195,rad:"魚",v:[],jp:"うお",m:"fish",k:[{c:"魚",m:"fish"},{c:"鮮",m:"fresh"},{c:"鯨",m:"whale"},{c:"鯛",m:"sea bream"},{c:"鮭",m:"salmon"},{c:"鰐",m:"alligator"},{c:"鮪",m:"tuna"}]},
{num:196,rad:"鳥",v:[],jp:"とり",m:"bird",k:[{c:"鳥",m:"bird"},{c:"鳴",m:"chirp"},{c:"鶏",m:"chicken"},{c:"鶴",m:"crane"},{c:"鷹",m:"hawk"},{c:"鳩",m:"pigeon"},{c:"鷲",m:"eagle"}]},
{num:197,rad:"鹵",v:[],jp:"ろ",m:"salt",k:[{c:"鹵",m:"salt"}]},
{num:198,rad:"鹿",v:[],jp:"しか",m:"deer",k:[{c:"鹿",m:"deer"},{c:"麗",m:"lovely"},{c:"麓",m:"foot of mountain"}]},
{num:199,rad:"麥",v:[],jp:"むぎ",m:"wheat",k:[{c:"麦",m:"barley"},{c:"麺",m:"noodles"}]},
{num:200,rad:"麻",v:[],jp:"あさ",m:"hemp",k:[{c:"麻",m:"hemp"},{c:"磨",m:"grind"},{c:"魔",m:"demon"}]},
{num:201,rad:"黃",v:[],jp:"きいろ",m:"yellow",k:[{c:"黄",m:"yellow"},{c:"横",m:"sideways"}]},
{num:202,rad:"黍",v:[],jp:"きび",m:"millet",k:[{c:"黍",m:"millet"}]},
{num:203,rad:"黑",v:[],jp:"くろ",m:"black",k:[{c:"黒",m:"black"},{c:"黙",m:"silence"},{c:"墨",m:"ink"}]},
{num:204,rad:"黹",v:[],jp:"ふつ",m:"embroidery",k:[{c:"黹",m:"embroidery"}]},
{num:205,rad:"黽",v:[],jp:"べん",m:"frog",k:[{c:"黽",m:"frog"}]},
{num:206,rad:"鼎",v:[],jp:"かなえ",m:"sacrificial tripod",k:[{c:"鼎",m:"tripod"}]},
{num:207,rad:"鼓",v:[],jp:"つづみ",m:"drum",k:[{c:"鼓",m:"drum"}]},
{num:208,rad:"鼠",v:[],jp:"ねずみ",m:"rat",k:[{c:"鼠",m:"rat"}]},
{num:209,rad:"鼻",v:[],jp:"はな",m:"nose",k:[{c:"鼻",m:"nose"}]},
{num:210,rad:"齊",v:[],jp:"せい",m:"even",k:[{c:"斉",m:"adjusted"},{c:"済",m:"settle"},{c:"剤",m:"dose"}]},
{num:211,rad:"齒",v:[],jp:"は",m:"tooth",k:[{c:"歯",m:"tooth"},{c:"齢",m:"age"}]},
{num:212,rad:"龍",v:[],jp:"りゅう",m:"dragon",k:[{c:"竜",m:"dragon"},{c:"龍",m:"dragon"},{c:"滝",m:"waterfall"}]},
{num:213,rad:"龜",v:[],jp:"かめ",m:"turtle",k:[{c:"亀",m:"tortoise"}]},
{num:214,rad:"龠",v:[],jp:"やく",m:"flute",k:[{c:"龠",m:"flute"}]}
];

module.exports = DATA;
